"""Observability namespace (`invarlock.observability`)."""

from __future__ import annotations

from . import alerting, core, exporters, health, metrics, utils
from .alerting import (
    Alert,
    AlertManager,
    AlertRule,
    AlertSeverity,
    AlertStatus,
    NotificationChannel,
    create_performance_alerts,
    create_resource_alerts,
    setup_email_notifications,
    setup_slack_notifications,
    setup_webhook_notifications,
)
from .core import (
    MonitoringConfig,
    MonitoringManager,
    PerformanceMonitor,
    ResourceMonitor,
    TelemetryCollector,
)
from .exporters import (
    ExportedMetric,
    ExportManager,
    InfluxDBExporter,
    JSONExporter,
    MetricsExporter,
    PrometheusExporter,
    StatsExporter,
    export_or_raise,
    setup_influxdb_exporter,
    setup_json_file_exporter,
    setup_prometheus_exporter,
    setup_statsd_exporter,
)
from .health import (
    ComponentHealth,
    HealthChecker,
    HealthStatus,
    InvarLockHealthChecker,
    create_health_endpoint,
)
from .metrics import (
    Counter,
    Gauge,
    Histogram,
    MetricsRegistry,
    MetricType,
    MetricValue,
    TimerContext,
    capture_memory_snapshot,
    create_operation_metrics,
    create_resource_metrics,
    reset_peak_memory_stats,
    summarize_memory_snapshots,
)
from .metrics import Timer as MetricsTimer
from .utils import (
    CircularBuffer,
    DebounceTimer,
    ExportError,
    HealthCheckError,
    MetricsCollectionError,
    MonitoringError,
    MovingAverage,
    PercentileCalculator,
    RateLimiter,
    ThresholdMonitor,
    Timer,
    TimingContext,
    clamp,
    exponential_backoff,
    format_bytes,
    format_duration,
    get_system_info,
    log_exceptions,
    retry_with_backoff,
    safe_divide,
    timed_operation,
    timing_decorator,
)

UtilityExportError = ExportError

__all__ = [
    "Alert",
    "AlertManager",
    "AlertRule",
    "AlertSeverity",
    "AlertStatus",
    "CircularBuffer",
    "ComponentHealth",
    "Counter",
    "DebounceTimer",
    "ExportError",
    "ExportManager",
    "ExportedMetric",
    "Gauge",
    "HealthCheckError",
    "HealthChecker",
    "HealthStatus",
    "Histogram",
    "InfluxDBExporter",
    "InvarLockHealthChecker",
    "JSONExporter",
    "MetricsCollectionError",
    "MetricsExporter",
    "MetricsRegistry",
    "MetricsTimer",
    "MetricType",
    "MetricValue",
    "MonitoringConfig",
    "MonitoringError",
    "MonitoringManager",
    "MovingAverage",
    "NotificationChannel",
    "PercentileCalculator",
    "PerformanceMonitor",
    "PrometheusExporter",
    "RateLimiter",
    "ResourceMonitor",
    "StatsExporter",
    "TelemetryCollector",
    "ThresholdMonitor",
    "Timer",
    "TimerContext",
    "TimingContext",
    "UtilityExportError",
    "alerting",
    "capture_memory_snapshot",
    "clamp",
    "core",
    "create_health_endpoint",
    "create_operation_metrics",
    "create_performance_alerts",
    "create_resource_metrics",
    "create_resource_alerts",
    "export_or_raise",
    "exporters",
    "exponential_backoff",
    "format_bytes",
    "format_duration",
    "get_system_info",
    "health",
    "log_exceptions",
    "metrics",
    "reset_peak_memory_stats",
    "retry_with_backoff",
    "safe_divide",
    "setup_email_notifications",
    "setup_influxdb_exporter",
    "setup_json_file_exporter",
    "setup_prometheus_exporter",
    "setup_slack_notifications",
    "setup_statsd_exporter",
    "setup_webhook_notifications",
    "summarize_memory_snapshots",
    "timed_operation",
    "timing_decorator",
    "utils",
]
