"""Public runtime-security API.

Implementation lives in `invarlock.runtime_security_helpers` plus the split
container and manifest owner modules that it imports.

Typed request-scoped policy surface retained at the owner boundary:
- class RuntimeSecurityPolicy
- def build_runtime_security_policy(
- policy: RuntimeSecurityPolicy | None = None
- ContextVar(
- def reset_runtime_allowances(
"""

from __future__ import annotations

from invarlock.runtime_security_helpers import (
    ALLOW_HOST_EXECUTION_ENV,
    ALLOW_NETWORK_ENV,
    ALLOW_REMOTE_CODE_ENV,
    ALLOW_THIRD_PARTY_PLUGINS_ENV,
    ALLOW_UNVERIFIED_PROVENANCE_ENV,
    CONTAINER_ENGINE_ENV,
    CONTAINER_EXECUTION_ENV,
    RUNTIME_IMAGE_CUDA_LOCAL_DEFAULT,
    RUNTIME_IMAGE_DEFAULT,
    RUNTIME_IMAGE_DIGEST_ENV,
    RUNTIME_IMAGE_ENV,
    RUNTIME_IMAGE_LOCAL_DEFAULT,
    RUNTIME_MANIFEST_FILENAME,
    RUNTIME_MANIFEST_VERSION,
    RUNTIME_VERIFIER_CONTRACT_VERSION,
    ContainerLaunchPlan,
    RuntimeManifestExecution,
    RuntimeManifestLoadIssueCode,
    RuntimeManifestLoadResult,
    RuntimeSecurityPolicy,
    apply_runtime_allowances,
    build_container_command,
    build_container_python_command,
    build_container_python_module_command,
    build_runtime_security_policy,
    container_image_available_locally,
    current_execution_mode,
    current_runtime_security_policy,
    delegate_container_command,
    delegate_python_module_to_container,
    delegate_python_script_to_container,
    host_execution_allowed,
    load_runtime_manifest,
    network_allowed,
    remote_code_allowed,
    reset_runtime_allowances,
    resolve_container_engine,
    resolve_runtime_image,
    resolve_runtime_image_digest,
    running_inside_container,
    runtime_allowances_scope,
    third_party_plugins_allowed,
    unverified_provenance_allowed,
    write_runtime_manifest,
)

__all__ = [
    "ALLOW_HOST_EXECUTION_ENV",
    "ALLOW_NETWORK_ENV",
    "ALLOW_REMOTE_CODE_ENV",
    "ALLOW_THIRD_PARTY_PLUGINS_ENV",
    "ALLOW_UNVERIFIED_PROVENANCE_ENV",
    "ContainerLaunchPlan",
    "RuntimeManifestExecution",
    "RuntimeSecurityPolicy",
    "CONTAINER_EXECUTION_ENV",
    "CONTAINER_ENGINE_ENV",
    "RUNTIME_IMAGE_DEFAULT",
    "RUNTIME_IMAGE_CUDA_LOCAL_DEFAULT",
    "RUNTIME_IMAGE_ENV",
    "RUNTIME_IMAGE_DIGEST_ENV",
    "RUNTIME_IMAGE_LOCAL_DEFAULT",
    "RUNTIME_MANIFEST_FILENAME",
    "RUNTIME_MANIFEST_VERSION",
    "RUNTIME_VERIFIER_CONTRACT_VERSION",
    "apply_runtime_allowances",
    "build_container_command",
    "build_container_python_module_command",
    "build_container_python_command",
    "build_runtime_security_policy",
    "container_image_available_locally",
    "current_execution_mode",
    "current_runtime_security_policy",
    "delegate_container_command",
    "delegate_python_module_to_container",
    "delegate_python_script_to_container",
    "network_allowed",
    "host_execution_allowed",
    "load_runtime_manifest",
    "remote_code_allowed",
    "resolve_container_engine",
    "resolve_runtime_image",
    "resolve_runtime_image_digest",
    "reset_runtime_allowances",
    "runtime_allowances_scope",
    "RuntimeManifestLoadIssueCode",
    "RuntimeManifestLoadResult",
    "running_inside_container",
    "third_party_plugins_allowed",
    "unverified_provenance_allowed",
    "write_runtime_manifest",
]
