"""Frozen captured-v2 contracts, independently authored and signed reference bytes.

The corpus is never regenerated by these tests. Mutations use reference JSON,
SHA-256 and Ed25519 operations, not the normalizer or publication implementation.
"""

import base64
import hashlib
import json
from pathlib import Path
from unittest.mock import Mock

import pytest
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from typer.testing import CliRunner

from invarlock import captured_contracts as contracts
from invarlock import captured_evaluation as evaluation
from invarlock import captured_reporting as reporting
from invarlock import captured_verification as verification
from invarlock import evidence_reporting
from invarlock.captured_evidence_publication import publish_captured_evidence
from invarlock.captured_normalization import (
    captured_comparison_id,
    captured_request_digest,
    comparison_policy_digest,
    normalize_captured_request,
)
from invarlock.cli.app import _setup_result, app
from invarlock.core import scoring
from invarlock.core.evaluation_request import load_evaluation_request
from invarlock.evaluation_comparison import comparison
from invarlock.evaluation_record_contracts.contracts import EvaluationRecordsError
from invarlock.evidence_pack_contract import canonical_json_bytes

CORPUS_PATH = (
    Path(__file__).parents[1] / "fixtures/evaluation_contracts/captured-v2.json"
)
CORPUS_BYTES = CORPUS_PATH.read_bytes()
CORPUS = json.loads(CORPUS_BYTES)
RUNNER = CliRunner()


def _canonical(value):
    return (
        json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            allow_nan=False,
        )
        + "\n"
    ).encode()


def _sha(raw):
    return "sha256:" + hashlib.sha256(raw).hexdigest()


def _raw(name):
    return CORPUS["artifacts"][name]["bytes"].encode()


def _value(name):
    return json.loads(_raw(name))


def _digest(name):
    return CORPUS["artifacts"][name]["digest"]


def _key(role):
    return Ed25519PrivateKey.from_private_bytes(
        bytes.fromhex(CORPUS["test_keys"][role]["seed_hex"])
    )


def _pem(role):
    return _key(role).private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )


def _write(path, raw):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(raw)


def _pack(root, name="pass", *, unsigned=False, request_b=False):
    pack = root / "pack"
    payloads = dict(CORPUS["cases"][name]["payloads"])
    control = "b" if request_b else name
    if request_b:
        payloads["request.json"] = "request-b.json"
    payloads["manifest.json"] = (
        f"manifest-{control}{'-unsigned' if unsigned else ''}.json"
    )
    payloads["checksums.sha256"] = f"ledger-{control}.sha256"
    if not unsigned:
        payloads["manifest.signature.json"] = f"signature-{control}.json"
    for path, artifact in payloads.items():
        _write(pack / path, _raw(artifact))
    return pack


def _verify_options(root, name="pass"):
    _write(root / "approved-policy.json", _raw("policy.json"))
    identity = _value(f"identity-{name}.json")
    return {
        "policy_path": root / "approved-policy.json",
        "expected_baseline_run": identity["baseline_run_digest"],
        "expected_subject_run": identity["subject_run_digest"],
        "expected_request_digest": identity["request_digest"],
        "expected_signer": CORPUS["test_keys"]["signer"]["fingerprint"],
        "receipt_path": root / "receipt.json",
        "verifier_signing_key_path": None,
        "verifier_signing_key_bytes": _pem("verifier"),
        "verifier_identity": "reviewed-verifier",
    }


def _authenticate(pack, options):
    return verification.verify_captured_receipt(
        options["receipt_path"],
        pack,
        **{
            name: options[name]
            for name in (
                "policy_path",
                "expected_baseline_run",
                "expected_subject_run",
                "expected_request_digest",
                "expected_signer",
            )
        },
        expected_verifier_identity="reviewed-verifier",
        expected_verifier_fingerprint=CORPUS["test_keys"]["verifier"]["fingerprint"],
    )


def _resign_receipt(path, receipt):
    receipt["signature"]["value"] = base64.b64encode(
        _key("verifier").sign(_canonical(receipt["statement"]))
    ).decode()
    _write(path, _canonical(receipt))


def _rebind(pack):
    manifest = json.loads((pack / "manifest.json").read_bytes())
    for ref in manifest["files"].values():
        ref["digest"] = _sha((pack / ref["path"]).read_bytes())
    manifest["request_digest"] = manifest["files"]["request"]["digest"]
    manifest["comparison_id"] = _sha(
        _canonical(
            {
                "kind": "captured",
                "request_digest": manifest["request_digest"],
                "baseline_run_digest": manifest["files"]["baseline"]["digest"],
                "subject_run_digest": manifest["files"]["subject"]["digest"],
                "policy_digest": manifest["files"]["policy"]["digest"],
            }
        )
    )
    ledger = "".join(
        f"{ref['digest'][7:]}  {ref['path']}\n"
        for ref in sorted(manifest["files"].values(), key=lambda ref: ref["path"])
    ).encode()
    manifest["checksums_sha256_digest"] = _sha(ledger)[7:]
    raw = _canonical(manifest)
    signature = _value("signature-pass.json")
    signature["signature"]["value"] = base64.b64encode(
        _key("signer").sign(raw)
    ).decode()
    _write(pack / "manifest.json", raw)
    _write(pack / "checksums.sha256", ledger)
    _write(pack / "manifest.signature.json", _canonical(signature))


def _request(root, *, request_b=False, output="evidence"):
    for name in ("baseline", "subject", "policy"):
        _write(
            root / f"{name}.json",
            _raw("subject-pass.json" if name == "subject" else f"{name}.json"),
        )
    authored = _value("authored-b.json" if request_b else "authored-pass.json")
    authored["output"]["evidence"] = output
    _write(root / "request.json", _canonical(authored))
    _write(root / "signer.pem", _pem("signer"))
    return load_evaluation_request(root / "request.json")


def test_reviewed_corpus_is_immutable_canonical_and_independently_signed():
    assert (
        hashlib.sha256(CORPUS_BYTES).hexdigest()
        == "9305e17276596604e7d382ebd7188d8cd94125578397e92430f5e36c2355ebf0"
    )
    assert len(CORPUS["artifacts"]) == 51
    # Adding setup variants must not change any of the original 46 vectors.
    original = {
        **CORPUS,
        "artifacts": {
            name: artifact
            for name, artifact in CORPUS["artifacts"].items()
            if not name.startswith(("setup-keygen-", "setup-freeze-cases-"))
        },
    }
    assert len(original["artifacts"]) == 46
    assert (
        hashlib.sha256(
            (json.dumps(original, sort_keys=True, indent=2) + "\n").encode()
        ).hexdigest()
        == "30752dac4d448d2bd86b4a3591d926048987e322e439043a260b0de676974abe"
    )
    for name, artifact in CORPUS["artifacts"].items():
        raw = artifact["bytes"].encode()
        assert _sha(raw) == artifact["digest"], name
        if name.endswith(".json"):
            assert _canonical(json.loads(raw)) == raw, name
            assert canonical_json_bytes(json.loads(raw)) == raw, name
        if name.startswith("signature-"):
            signature = json.loads(raw)
            manifest_raw = _raw(name.replace("signature-", "manifest-"))
            _key("signer").public_key().verify(
                base64.b64decode(signature["signature"]["value"]), manifest_raw
            )
            assert (
                contracts.manifest_signature(manifest_raw, _key("signer")) == signature
            )
        if name.startswith("receipt-"):
            receipt = json.loads(raw)
            _key("verifier").public_key().verify(
                base64.b64decode(receipt["signature"]["value"]),
                _canonical(receipt["statement"]),
            )


@pytest.mark.parametrize("name", ["pass", "regression", "insufficient"])
def test_literal_normalization_identity_and_analytic_comparison(name):
    baseline, subject, policy = (
        _value("baseline.json"),
        _value(f"subject-{name}.json"),
        _value("policy.json"),
    )
    normalized = normalize_captured_request(
        _value(f"authored-{name}.json"),
        baseline=baseline,
        subject=subject,
        policy=policy,
    )
    assert normalized == _value(f"request-{name}.json")
    assert captured_request_digest(normalized) == _digest(f"request-{name}.json")
    assert comparison_policy_digest(policy) == _digest("policy.json")
    identity = _value(f"identity-{name}.json")
    assert captured_comparison_id(
        **{k: v for k, v in identity.items() if k != "kind"}
    ) == _digest(f"identity-{name}.json")
    result = comparison.compare_runs(baseline, subject, policy)
    assert result == _value(f"comparison-{name}.json")
    assert canonical_json_bytes(result) == _raw(f"comparison-{name}.json")
    assert _digest(f"identity-{name}.json") != _digest(f"comparison-{name}.json")


@pytest.mark.parametrize("name", ["pass", "regression", "insufficient"])
@pytest.mark.parametrize("unsigned", [False, True])
def test_publication_matches_every_frozen_byte(tmp_path, name, unsigned):
    key = tmp_path / "signer.pem"
    key.write_bytes(_pem("signer"))
    published = tmp_path / "published"
    publish_captured_evidence(
        published,
        baseline=_value("baseline.json"),
        subject=_value(f"subject-{name}.json"),
        policy=_value("policy.json"),
        comparison=_value(f"comparison-{name}.json"),
        normalized_request=_value(f"request-{name}.json"),
        request_digest=_digest(f"request-{name}.json"),
        signing_key_path=None if unsigned else key,
        unsigned=unsigned,
    )
    expected = _pack(tmp_path, name, unsigned=unsigned)
    assert {
        p.relative_to(published): p.read_bytes()
        for p in published.rglob("*")
        if p.is_file()
    } == {
        p.relative_to(expected): p.read_bytes()
        for p in expected.rglob("*")
        if p.is_file()
    }
    with contracts.captured_snapshot(published) as snapshot:
        manifest, payloads, _ = contracts.load_payloads(snapshot)
    assert manifest["comparison_id"] == _digest(f"identity-{name}.json")
    assert payloads["report"] == _value(f"comparison-{name}.json")


def test_request_intent_changes_id_but_paths_keys_and_republication_do_not(tmp_path):
    ids = []
    for name, request_b, signer_role in [
        ("a", False, "signer"),
        ("relocated", False, "verifier"),
        ("b", True, "signer"),
    ]:
        request = _request(
            tmp_path / name,
            request_b=request_b,
            output="other" if name == "relocated" else "evidence",
        )
        key = request.root / "signer.pem"
        key.write_bytes(_pem(signer_role))
        result = evaluation.evaluate_captured_request(request, signing_key_path=key)
        ids.append(result.comparison_id)
        assert (
            request.evidence / "reports/evaluation.report.json"
        ).read_bytes() == _raw("comparison-pass.json")
        assert (request.evidence / "request.json").read_bytes() == _raw(
            "request-b.json" if request_b else "request-pass.json"
        )
    assert ids == [
        _digest("identity-pass.json"),
        _digest("identity-pass.json"),
        _digest("identity-b.json"),
    ]
    assert ids[0] != ids[2]


@pytest.mark.parametrize("name", ["pass", "regression", "insufficient"])
def test_replay_and_receipt_match_frozen_signed_statements(tmp_path, name):
    pack, options = _pack(tmp_path, name), _verify_options(tmp_path, name)
    result = verification.verify_captured_evidence(pack, **options)
    assert result["decision"] == CORPUS["cases"][name]["decision"]
    assert result["ok"] is (name == "pass")
    assert options["receipt_path"].read_bytes() == _raw(f"receipt-{name}.json")
    authenticated = _authenticate(pack, options)
    assert authenticated.ok
    assert authenticated.statement == _value(f"receipt-{name}.json")["statement"]


def test_expected_a_examined_b_authentic_rejection_never_follows_payloads(
    tmp_path, monkeypatch
):
    pack, options = _pack(tmp_path, request_b=True), _verify_options(tmp_path)
    forbidden = Mock(side_effect=AssertionError("rejected request reached replay"))
    monkeypatch.setattr(verification, "compare_runs", forbidden)
    with pytest.raises(
        verification.CapturedVerificationError,
        match="request differs from expected anchor",
    ):
        verification.verify_captured_evidence(pack, **options)
    forbidden.assert_not_called()
    assert options["receipt_path"].read_bytes() == _raw(
        "receipt-integrity-rejection.json"
    )
    for path in pack.rglob("*"):
        if path.is_file() and path.name != "manifest.json":
            path.unlink()
    reads = Mock(wraps=verification.read_file)
    monkeypatch.setattr(verification, "read_file", reads)
    authenticated = _authenticate(pack, options)
    assert authenticated.ok
    assert (
        authenticated.statement
        == _value("receipt-integrity-rejection.json")["statement"]
    )
    assert [call.args[0] for call in reads.call_args_list] == [
        options["receipt_path"],
        options["policy_path"],
        pack / "manifest.json",
    ]
    assert not _authenticate(
        pack, {**options, "expected_request_digest": _digest("request-b.json")}
    ).ok


@pytest.mark.parametrize(
    "mutation",
    ["unknown", "path", "format", "pin", "override", "run_digest", "policy_digest"],
)
def test_resigned_normalized_request_fails_before_presentation_or_replay(
    tmp_path, monkeypatch, mutation
):
    pack, options = _pack(tmp_path), _verify_options(tmp_path)
    request = _value("request-pass.json")
    source = request["comparison"]["baseline"]
    if mutation == "unknown":
        request["unknown"] = True
    elif mutation == "path":
        source["path"] = "/outside/request.json"
    elif mutation == "format":
        request["format"] = "invarlock/evaluation-request-v2-normalized"
    elif mutation == "override":
        source["run_id"] = "override"
    elif mutation in {"pin", "run_digest"}:
        source["expected_run_digest" if mutation == "pin" else "run_digest"] = (
            "sha256:" + "0" * 64
        )
    else:
        request["comparison"]["policy_digest"] = "sha256:" + "0" * 64
    _write(pack / "request.json", _canonical(request))
    _rebind(pack)
    forbidden = Mock(side_effect=AssertionError("invalid snapshot reached consumer"))
    monkeypatch.setattr(reporting, "_view", forbidden)
    monkeypatch.setattr(verification, "compare_runs", forbidden)
    with pytest.raises(evidence_reporting.EvidenceReportError):
        evidence_reporting.render_evidence(pack)
    with pytest.raises(verification.CapturedVerificationError) as failure:
        verification.verify_captured_evidence(pack, **options)
    assert failure.value.exit_code == (
        6 if mutation in {"run_digest", "policy_digest"} else 4
    )
    assert _authenticate(pack, options).ok
    forbidden.assert_not_called()


@pytest.mark.parametrize(
    "field",
    ["source", "run_id", "artifact_digest", "score_provenance", "source_digest"],
)
def test_resigned_import_intent_must_agree_with_run(tmp_path, monkeypatch, field):
    pack, options = _pack(tmp_path), _verify_options(tmp_path)
    baseline, request, report = (
        _value("baseline.json"),
        _value("request-pass.json"),
        _value("comparison-pass.json"),
    )
    baseline["source_digest"] = "sha256:" + "3" * 64
    source = {
        "adapter": "jsonl",
        **{
            k: baseline[k]
            for k in ("source", "run_id", "artifact_digest", "score_provenance")
        },
        "run_digest": _sha(_canonical(baseline)),
    }
    request["comparison"]["baseline"] = source
    report["bindings"]["baseline"] = source["run_digest"]
    for path, value in [
        ("records/baseline.json", baseline),
        ("request.json", request),
        ("reports/evaluation.report.json", report),
    ]:
        _write(pack / path, _canonical(value))
    _rebind(pack)
    # Establish that this imported intent is valid before contradicting one field.
    with contracts.captured_snapshot(pack) as snapshot:
        contracts.load_payloads(snapshot)
    if field == "source_digest":
        baseline[field] = None
        source["run_digest"] = _sha(_canonical(baseline))
        report["bindings"]["baseline"] = source["run_digest"]
    else:
        source[field] = {
            "source": {"name": "other", "version": "1"},
            "run_id": "other",
            "artifact_digest": "sha256:" + "4" * 64,
            "score_provenance": {},
        }[field]
    for path, value in [
        ("records/baseline.json", baseline),
        ("request.json", request),
        ("reports/evaluation.report.json", report),
    ]:
        _write(pack / path, _canonical(value))
    _rebind(pack)
    forbidden = Mock(side_effect=AssertionError("inconsistent source reached consumer"))
    monkeypatch.setattr(reporting, "_view", forbidden)
    monkeypatch.setattr(verification, "compare_runs", forbidden)
    with pytest.raises(evidence_reporting.EvidenceReportError):
        evidence_reporting.render_evidence(pack)
    with pytest.raises(verification.CapturedVerificationError) as failure:
        verification.verify_captured_evidence(pack, **options)
    assert failure.value.exit_code == 6
    assert _authenticate(pack, options).ok
    forbidden.assert_not_called()


@pytest.mark.parametrize("role", ["baseline", "subject", "policy"])
def test_resigned_whole_comparison_bindings_fail_before_consumers(
    tmp_path, monkeypatch, role
):
    pack, options = _pack(tmp_path), _verify_options(tmp_path)
    report = _value("comparison-pass.json")
    report["bindings"][role] = "sha256:" + "0" * 64
    _write(pack / "reports/evaluation.report.json", _canonical(report))
    _rebind(pack)
    forbidden = Mock(side_effect=AssertionError("inconsistent report reached consumer"))
    monkeypatch.setattr(reporting, "_view", forbidden)
    monkeypatch.setattr(verification, "compare_runs", forbidden)
    with pytest.raises(
        evidence_reporting.EvidenceReportError, match="comparison contradicts"
    ):
        evidence_reporting.render_evidence(pack)
    with pytest.raises(
        verification.CapturedVerificationError, match="comparison contradicts"
    ):
        verification.verify_captured_evidence(pack, **options)
    forbidden.assert_not_called()


@pytest.mark.parametrize(
    "name,status,replay",
    [
        ("pass", 7, "completed"),
        ("regression", 0, "completed"),
        ("insufficient", 6, "completed"),
        ("integrity-rejection", 4, "failed"),
        ("integrity-rejection", 4, "completed"),
        ("pass", 0, "not_started"),
    ],
)
def test_resigned_contradictory_receipt_status_is_not_authentic(
    tmp_path, name, status, replay
):
    case = "pass" if name == "integrity-rejection" else name
    pack, options = (
        _pack(tmp_path, case, request_b=name == "integrity-rejection"),
        _verify_options(tmp_path, case),
    )
    receipt = _value(f"receipt-{name}.json")
    receipt["statement"]["verdict"]["verification_status"] = status
    receipt["statement"]["replay_status"] = replay
    _resign_receipt(options["receipt_path"], receipt)
    assert not _authenticate(pack, options).ok


def test_positive_receipt_rejects_report_digest_as_comparison_id(tmp_path):
    pack, options = _pack(tmp_path), _verify_options(tmp_path)
    manifest = _value("manifest-pass.json")
    manifest["comparison_id"] = manifest["files"]["report"]["digest"]
    raw = _canonical(manifest)
    _write(pack / "manifest.json", raw)
    receipt = _value("receipt-pass.json")
    receipt["statement"]["pack_manifest_digest"] = _sha(raw)
    _resign_receipt(options["receipt_path"], receipt)
    authenticated = _authenticate(pack, options)
    assert not authenticated.ok
    assert "contradicts manifest identity" in authenticated.errors[0]


@pytest.mark.parametrize(
    "kind,reference,config,message",
    [
        (
            "exact_match",
            {},
            {},
            "text scorer requires string expected and output values",
        ),
        ("numeric_tolerance", "invalid", {}, "numeric reference must be finite"),
        ("json_exact", "{", {}, "JSON reference must be a valid finite JSON value"),
        (
            "json_fields",
            {},
            {"fields": ["/answer"]},
            "reference must contain every configured JSON field",
        ),
    ],
)
def test_typed_invalid_references_preserve_native_metric_messages(
    kind, reference, config, message
):
    with pytest.raises(scoring.InvalidScoringReference) as error:
        scoring.score(kind, reference, "yes", config)
    assert isinstance(error.value, scoring.MetricError)
    assert str(error.value) == message


@pytest.mark.parametrize(
    "error,reason",
    [
        (
            scoring.UnsupportedScoringEnvironment("opaque environment"),
            "unsupported_scoring_environment",
        ),
        (
            comparison.LocalWorkBudgetExceeded("opaque allowance"),
            "local_work_budget_exceeded",
        ),
        (OSError("opaque I/O"), "verification_io_error"),
        (ValueError("Unicode local budget"), "verification_internal_error"),
    ],
)
@pytest.mark.parametrize("wrapped", [False, True])
def test_typed_replay_failures_do_not_depend_on_message_text(
    tmp_path, monkeypatch, error, reason, wrapped
):
    pack, options = _pack(tmp_path), _verify_options(tmp_path)
    if wrapped:
        outer = EvaluationRecordsError("opaque wrapper")
        outer.__cause__ = error
        error = outer
    monkeypatch.setattr(verification, "compare_runs", Mock(side_effect=error))
    with pytest.raises(verification.CapturedVerificationIncomplete, match=reason):
        verification.verify_captured_evidence(pack, **options)
    assert not options["receipt_path"].exists()


@pytest.mark.parametrize("wrapped", [False, True])
def test_typed_reference_failure_is_signed_rejection_not_environment_refusal(
    tmp_path, monkeypatch, wrapped
):
    pack, options = _pack(tmp_path), _verify_options(tmp_path)
    with pytest.raises(scoring.InvalidScoringReference) as failure:
        scoring.score("numeric_tolerance", "invalid target", 1)
    error = failure.value
    if wrapped:
        outer = EvaluationRecordsError("Unicode local budget are just words")
        outer.__cause__ = error
        error = outer
    monkeypatch.setattr(verification, "compare_runs", Mock(side_effect=error))
    with pytest.raises(verification.CapturedVerificationError, match="replay failed"):
        verification.verify_captured_evidence(pack, **options)
    authenticated = _authenticate(pack, options)
    assert authenticated.ok
    assert authenticated.statement["replay_status"] == "failed"
    assert authenticated.statement["verdict"]["verification_status"] == 6


def test_portable_unicode_authentication_and_pre_scorer_refusal(tmp_path, monkeypatch):
    pack, options = _pack(tmp_path), _verify_options(tmp_path)
    policy, request, report = (
        _value("policy.json"),
        _value("request-pass.json"),
        _value("comparison-pass.json"),
    )
    metric = policy["metrics"][0]
    metric.update(
        kind="token_f1", configuration={"unicode_version": "0.0.0"}, unit="score"
    )
    del metric["score_key"], metric["accepted_provenance"]
    policy_digest = _sha(_canonical(policy))
    request["comparison"]["policy_digest"] = policy_digest
    report["bindings"]["policy"] = policy_digest
    report["metrics"][0].update(
        kind="token_f1",
        unit="score",
        scoring_assurance="recomputed",
        baseline_mean=1.0,
        subject_mean=1.0,
        delta=0.0,
        interval={
            "lower": 0.0,
            "upper": 0.0,
            "method": "paired_mean_shake256_percentile_v1",
            "mass": 0.95,
            "replicates": 2048,
        },
    )
    for path, value in [
        ("inputs/policy.json", policy),
        ("request.json", request),
        ("reports/evaluation.report.json", report),
    ]:
        _write(pack / path, _canonical(value))
    _rebind(pack)
    options["policy_path"].write_bytes(_canonical(policy))
    options["expected_request_digest"] = _sha(_canonical(request))
    forbidden = Mock(
        side_effect=AssertionError("portable authentication called scorer")
    )
    monkeypatch.setattr(verification, "compare_runs", forbidden)
    monkeypatch.setattr(comparison, "score", forbidden)
    assert comparison_policy_digest(policy) == policy_digest
    rendered = evidence_reporting.render_evidence(pack)
    assert isinstance(rendered, evidence_reporting.EvidenceReportV2)
    assert "Not performed by report" in rendered.text
    receipt = _value("receipt-pass.json")
    receipt["statement"]["anchors"].update(
        policy_digest=policy_digest, request_digest=options["expected_request_digest"]
    )
    receipt["statement"]["pack_manifest_digest"] = _sha(
        (pack / "manifest.json").read_bytes()
    )
    receipt["statement"]["scoring_assurance"][0].update(
        kind="token_f1", scoring_assurance="recomputed"
    )
    _resign_receipt(options["receipt_path"], receipt)
    assert _authenticate(pack, options).ok
    options["receipt_path"].unlink()
    with pytest.raises(
        verification.CapturedVerificationIncomplete,
        match="unsupported_scoring_environment",
    ):
        verification.verify_captured_evidence(pack, **options)
    assert not options["receipt_path"].exists()
    forbidden.assert_not_called()
    with pytest.raises(scoring.UnsupportedScoringEnvironment) as error:
        scoring.validate_configuration("token_f1", metric["configuration"])
    assert (
        str(error.value)
        == f"token_f1 requires Unicode '0.0.0'; this runtime provides {scoring.unicodedata.unidata_version}. Use a runtime with the policy's Unicode version."
    )
    # A mismatched host must not bypass portable validation of another metric.
    policy["metrics"].append({**metric, "kind": "recorded"})
    options["policy_path"].write_bytes(_canonical(policy))
    with pytest.raises(
        verification.CapturedVerificationIncomplete, match="invalid verification inputs"
    ):
        verification.verify_captured_evidence(pack, **options)
    assert not options["receipt_path"].exists()
    assert not _authenticate(pack, options).ok


def test_frozen_preflight_result_error_report_and_setup_fields(tmp_path, monkeypatch):
    request = _request(tmp_path)
    forbidden = Mock(side_effect=AssertionError("preflight invoked comparison"))
    with monkeypatch.context() as scoped:
        scoped.setattr(evaluation, "compare_runs", forbidden)
        result = evaluation.preflight_captured_request(
            request, signing_key_path=tmp_path / "signer.pem"
        )
        assert result.as_json().replace(str(tmp_path), "<root>").encode() == _raw(
            "preflight-success.json"
        )
        for preflight, artifact in [
            (True, "preflight-failure.json"),
            (False, "evaluation-error-v2.json"),
        ]:
            args = [
                "evaluate",
                str(tmp_path / "request.json"),
                "--signing-key",
                str(tmp_path / "signer.pem"),
                "--max-bootstrap-draws",
                "0",
                "--json",
            ]
            if preflight:
                args.append("--preflight")
            failure = RUNNER.invoke(app, args)
            assert failure.exit_code == 2, failure.output
            assert json.loads(failure.stdout) == _value(artifact)
        forbidden.assert_not_called()
        assert not request.evidence.exists()
    result = evaluation.evaluate_captured_request(
        request, signing_key_path=tmp_path / "signer.pem"
    )
    assert result.as_json().replace(str(tmp_path), "<root>").encode() == _raw(
        "evaluation-result-v2.json"
    )
    report = RUNNER.invoke(app, ["report", str(request.evidence), "--json"])
    assert report.exit_code == 0, report.output
    assert json.loads(report.stdout) == _value("report-v2.json")
    success, failure = _value("setup-success.json"), _value("setup-failure.json")
    assert _setup_result("init", details=success["details"]) == success
    assert _setup_result("init", errors=failure["errors"]) == failure


@pytest.mark.parametrize("variant", ["success", "failure"])
def test_frozen_keygen_setup(tmp_path, monkeypatch, variant):
    directory = tmp_path / "keys"
    existing = variant == "failure"
    role = "verifier" if existing else "signer"
    expected_files = {
        "private.pem": _pem(role),
        "public.pem": CORPUS["test_keys"][role]["public_key_pem"].encode(),
    }
    if existing:
        directory.mkdir()
        for name, raw in expected_files.items():
            (directory / name).write_bytes(raw)

    # RFC 8032 test 1, documented in the corpus; never use generated CLI values
    # to construct the expected fingerprint or key material.
    key = _key("signer")
    assert (
        _sha(
            key.public_key().public_bytes(
                serialization.Encoding.Raw, serialization.PublicFormat.Raw
            )
        )
        == CORPUS["test_keys"]["signer"]["fingerprint"]
    )
    generate = Mock(return_value=key)
    monkeypatch.setattr(Ed25519PrivateKey, "generate", generate)
    result = RUNNER.invoke(app, ["evaluate", "--keygen", str(directory), "--json"])
    assert result.exit_code == (2 if existing else 0), result.output
    assert result.stderr == ""
    stdout = result.stdout
    if existing:
        generate.assert_not_called()
    else:
        generate.assert_called_once_with()
        for name in expected_files:
            path = str(directory / name)
            assert stdout.count(path) == 1
            stdout = stdout.replace(path, f"<root>/keys/{name}")
    # Typer adds one framing LF after the canonical JSON's own trailing LF.
    assert stdout.encode() == _raw(f"setup-keygen-{variant}.json") + b"\n"
    assert set(tmp_path.iterdir()) == {directory}
    assert {path.name: path.read_bytes() for path in directory.iterdir()} == (
        expected_files
    )


@pytest.mark.parametrize("variant", ["success", "output-success", "failure"])
def test_frozen_freeze_cases_setup(tmp_path, monkeypatch, variant):
    # Literal approved membership, with its independently computed SHA-256.
    approved = (
        b'{"cases":[{"expected":"yes","id":"a","input":"first","metadata":{}},'
        b'{"expected":"yes","id":"b","input":"second","metadata":{}}],'
        b'"format":"invarlock/evaluation-case-set-v1"}\n'
    )
    assert _canonical(json.loads(approved)) == approved
    assert _sha(approved) == (
        "sha256:799d0a3b15d9a811ea2a9d118af0333aeb8e103bcd95cc62832a34c57ccdef14"
    )
    authored = json.loads(approved)
    authored["cases"].reverse()
    source = tmp_path / "planned.json"
    source_raw = json.dumps(authored, indent=2).encode()
    source.write_bytes(source_raw)
    output = tmp_path / "canonical.json"
    expected_files = {source: source_raw}
    if variant == "failure":
        expected_files[output] = b"approved destination: do not overwrite\n"
        output.write_bytes(expected_files[output])

    monkeypatch.chdir(tmp_path)
    # Pin only the staging filename; keep real no-replace filesystem publication.
    token_hex = Mock(return_value="0" * 32)
    monkeypatch.setattr(contracts.secrets, "token_hex", token_hex)
    args = ["evaluate", "--freeze-cases", str(source), "--json"]
    if variant != "success":
        args.extend(["--case-set-output", str(output)])
    result = RUNNER.invoke(app, args)
    assert result.exit_code == (2 if variant == "failure" else 0), result.output
    assert result.stderr == ""
    stdout = result.stdout
    if variant == "output-success":
        assert stdout.count(str(output)) == 1
        stdout = stdout.replace(str(output), "<root>/canonical.json")
        expected_files[output] = approved
    assert stdout.encode() == _raw(f"setup-freeze-cases-{variant}.json") + b"\n"
    if variant == "success":
        token_hex.assert_not_called()
    else:
        token_hex.assert_called_once_with(16)
    assert {path: path.read_bytes() for path in tmp_path.iterdir()} == expected_files
