"""Facade for evaluation-report verification helpers."""

from __future__ import annotations

from . import verify_check_helpers_impl as _impl

_VERIFY_PARSE_EXCEPTIONS = _impl._VERIFY_PARSE_EXCEPTIONS
_coerce_float = _impl._coerce_float
_coerce_int = _impl._coerce_int
_load_evaluation_report = _impl._load_evaluation_report
_validate_report_schema_strict = _impl._validate_report_schema_strict
_validate_logspace_ci_identity = _impl._validate_logspace_ci_identity
_validate_primary_metric = _impl._validate_primary_metric
_recompute_validation_flags = _impl._recompute_validation_flags
_validate_primary_metric_policy = _impl._validate_primary_metric_policy
_validate_release_gate_outcomes = _impl._validate_release_gate_outcomes
_validate_pairing = _impl._validate_pairing
_validate_counts = _impl._validate_counts
_validate_drift_band = _impl._validate_drift_band
_validate_tokenizer_hash = _impl._validate_tokenizer_hash
_resolve_path = _impl._resolve_path
_measurement_contract_digest = _impl._measurement_contract_digest
_validate_measurement_contracts = _impl._validate_measurement_contracts
_validate_variance_enablement = _impl._validate_variance_enablement
_apply_profile_lints = _impl._apply_profile_lints
_validate_evaluation_report_payload = _impl._validate_evaluation_report_payload
_report_schema = _impl._report_schema
REPORT_JSON_SCHEMA = _impl.REPORT_JSON_SCHEMA
REPORT_SCHEMA_VERSION = _impl.REPORT_SCHEMA_VERSION
validate_report = _impl.validate_report
compute_validation_flags = _impl.compute_validation_flags
resolve_pm_acceptance_range_from_report = _impl.resolve_pm_acceptance_range_from_report
resolve_pm_drift_band_from_report = _impl.resolve_pm_drift_band_from_report
resolve_tiny_relax_from_report = _impl.resolve_tiny_relax_from_report

__all__ = list(_impl.__all__)
