"""Retained ownership and cleanup for private directory publication attempts."""

from __future__ import annotations

import os
import secrets
import stat
from collections.abc import Callable, Iterator, Mapping
from contextlib import contextmanager, suppress
from dataclasses import dataclass
from pathlib import Path

from .atomic_directory import publish_directory_no_replace
from .paths import PathChangedError, entry_identity, pinned_directory

_FLAGS = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC
_MAX_DEPTH = 16


def _snapshot_identity(value: os.stat_result) -> tuple[int, ...]:
    return (*entry_identity(value), value.st_size, value.st_mtime_ns, value.st_ctime_ns)


def _require_file_bytes(parent: int, name: str, expected: bytes) -> None:
    before = os.stat(name, dir_fd=parent, follow_symlinks=False)
    if not stat.S_ISREG(before.st_mode) or before.st_size != len(expected):
        raise PathChangedError("staged file does not match generated bytes")
    descriptor = os.open(
        name, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK | os.O_CLOEXEC, dir_fd=parent
    )
    try:
        identity = _snapshot_identity(before)
        if _snapshot_identity(os.fstat(descriptor)) != identity:
            raise PathChangedError("staged file identity changed while opening")
        offset = 0
        while chunk := os.read(descriptor, min(65536, len(expected) - offset + 1)):
            if chunk != expected[offset : offset + len(chunk)]:
                raise PathChangedError("staged file does not match generated bytes")
            offset += len(chunk)
        named = os.stat(name, dir_fd=parent, follow_symlinks=False)
        if (
            offset != len(expected)
            or _snapshot_identity(os.fstat(descriptor)) != identity
            or _snapshot_identity(named) != identity
        ):
            raise PathChangedError("staged file identity changed while reading")
    finally:
        try:
            os.close(descriptor)
        except OSError:
            pass


def _require_exact_tree(
    descriptor: int, expected: Mapping[str, bytes], *, depth: int = 0
) -> None:
    if depth > _MAX_DEPTH:
        raise PathChangedError("generated directory nesting exceeds validation limit")
    before = _snapshot_identity(os.fstat(descriptor))
    files: dict[str, bytes] = {}
    directories: dict[str, dict[str, bytes]] = {}
    for path, payload in expected.items():
        name, separator, remainder = path.partition("/")
        if separator:
            directories.setdefault(name, {})[remainder] = payload
        else:
            files[name] = payload
    if set(os.listdir(descriptor)) != files.keys() | directories.keys():
        raise PathChangedError(
            "staged directory inventory does not match generated files"
        )
    for name, payload in files.items():
        _require_file_bytes(descriptor, name, payload)
    for name, children in directories.items():
        child = _open_owned_child(descriptor, name)
        try:
            _require_exact_tree(child, children, depth=depth + 1)
            named = os.stat(name, dir_fd=descriptor, follow_symlinks=False)
            if entry_identity(named) != entry_identity(os.fstat(child)):
                raise PathChangedError(
                    "staged directory identity changed while reading"
                )
        finally:
            try:
                os.close(child)
            except OSError:
                pass
    if _snapshot_identity(os.fstat(descriptor)) != before:
        raise PathChangedError(
            "staged directory changed while validating generated files"
        )


def _open_owned_child(parent: int, name: str) -> int:
    before = os.stat(name, dir_fd=parent, follow_symlinks=False)
    descriptor = os.open(name, _FLAGS, dir_fd=parent)
    try:
        opened = os.fstat(descriptor)
        if (
            entry_identity(before) != entry_identity(opened)
            or opened.st_uid != os.geteuid()
        ):
            raise PathChangedError("private staging directory identity changed")
    except BaseException:
        try:
            os.close(descriptor)
        except OSError:
            pass
        raise
    return descriptor


def _change_tree(descriptor: int, *, remove: bool, depth: int = 0) -> None:
    if depth > _MAX_DEPTH:
        raise OSError("private staging directory nesting exceeds cleanup limit")
    if remove:
        os.fchmod(descriptor, 0o700)
    for name in os.listdir(descriptor):
        before = os.stat(name, dir_fd=descriptor, follow_symlinks=False)
        if stat.S_ISDIR(before.st_mode):
            child = _open_owned_child(descriptor, name)
            try:
                _change_tree(child, remove=remove, depth=depth + 1)
                if remove:
                    named = os.stat(name, dir_fd=descriptor, follow_symlinks=False)
                    if entry_identity(named) == entry_identity(os.fstat(child)):
                        os.rmdir(name, dir_fd=descriptor)
            finally:
                try:
                    os.close(child)
                except OSError:
                    pass
        elif remove:
            os.unlink(name, dir_fd=descriptor)
    if not remove:
        os.fchmod(descriptor, 0o555)


@dataclass
class StagedDirectory:
    path: Path
    destination: Path
    descriptor: int
    parent_descriptor: int
    published: bool = False

    def require_exact_files(self, expected: Mapping[str, bytes]) -> None:
        """Compare the retained tree to generated bytes, independent of its path."""
        for name in expected:
            path = Path(name)
            if path.is_absolute() or any(
                part in {"", ".", ".."} for part in name.split("/")
            ):
                raise ValueError(
                    "generated file names must be relative without traversal"
                )
        _require_exact_tree(self.descriptor, expected)

    def make_read_only(self) -> None:
        """Apply directory modes through owned descriptors, never output paths."""
        _change_tree(self.descriptor, remove=False)

    def require_published_binding(self) -> None:
        """Recheck ownership after callers finalize or reload a published tree."""
        named = os.stat(
            self.destination.name,
            dir_fd=self.parent_descriptor,
            follow_symlinks=False,
        )
        if entry_identity(named) != entry_identity(os.fstat(self.descriptor)):
            raise PathChangedError(
                "published directory identity changed; destination retained"
            )

    def publish(
        self, publisher: Callable[..., None] = publish_directory_no_replace
    ) -> None:
        publisher(
            self.path,
            self.destination,
            expected_source_fd=self.descriptor,
            expected_source_parent_fd=self.parent_descriptor,
        )
        self.published = True

    def cleanup(self) -> None:
        """Never traverse the old stage name or clean a possibly committed tree.

        Recursion is limited to the retained private root and owned child FDs.
        Processes sharing the caller's filesystem identity must be trusted not
        to mutate those private directories concurrently.
        """
        if self.published:
            return
        with suppress(OSError):
            named = os.stat(
                self.path.name, dir_fd=self.parent_descriptor, follow_symlinks=False
            )
            if entry_identity(named) != entry_identity(os.fstat(self.descriptor)):
                return
            _change_tree(self.descriptor, remove=True)
            named = os.stat(
                self.path.name, dir_fd=self.parent_descriptor, follow_symlinks=False
            )
            if entry_identity(named) == entry_identity(os.fstat(self.descriptor)):
                os.rmdir(self.path.name, dir_fd=self.parent_descriptor)


@contextmanager
def staged_directory(
    destination: Path, *, prefix: str, create_parents: bool = False
) -> Iterator[StagedDirectory]:
    """Create and pin a private stage before any caller writes into its path."""
    destination = Path(destination).absolute()
    with pinned_directory(destination.parent, create=create_parents) as parent:
        name = prefix + secrets.token_hex(16)
        os.mkdir(name, mode=0o700, dir_fd=parent)
        try:
            descriptor = _open_owned_child(parent, name)
        except BaseException:
            with suppress(OSError):
                os.rmdir(name, dir_fd=parent)
            raise
        stage: StagedDirectory | None = None
        try:
            stage = StagedDirectory(
                destination.parent / name, destination, descriptor, parent
            )
            try:
                yield stage
            finally:
                stage.cleanup()
        finally:
            if stage is None:
                with suppress(OSError):
                    os.rmdir(name, dir_fd=parent)
            try:
                os.close(descriptor)
            except OSError:
                pass
