#!/usr/bin/env python3
"""Render the evaluator documentation matrix from retained manifests."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parents[1]
DOCUMENT = REPO / "docs" / "reference" / "evaluator-qualification.md"
START = "<!-- evaluator-matrix:start -->"
END = "<!-- evaluator-matrix:end -->"


def load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_bytes())
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain an object")
    return value


def pinned_version(profile: dict[str, Any]) -> str:
    package = profile["upstream"]
    lock = (ROOT / profile["lock"]).read_text(encoding="utf-8").strip()
    if "git+" in lock:
        revision = lock.rsplit("@", 1)[-1]
        return f"source revision `{revision[:7]}` (`{package['version']}`)"
    separator = "@" if package["ecosystem"] == "npm" else "=="
    return f"`{package['name']}{separator}{package['version']}`"


def adapter_support(profile: dict[str, Any]) -> str:
    if profile["support_status"] != "maintained_adapter":
        raise ValueError("unsupported adapter support status")
    return "Maintained"


def replay_authority(profile: dict[str, Any]) -> str:
    authority = profile["authority"]
    if authority["mode"] == "deterministic_per_record":
        return "Independently replayable"
    reason = str(authority["reason"]).replace("_", " ")
    return f"Observation-only: {reason}"


def escape_cell(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", " ")


def retained_transactions(value: object) -> str:
    if value == []:
        return "—"
    if not isinstance(value, list) or not value:
        raise ValueError("retained signed transaction status is invalid")
    counts: set[int] = set()
    packages: set[str] = set()
    for claim in value:
        if (
            not isinstance(claim, dict)
            or set(claim) != {"dataset_name", "package_id", "record_count", "role"}
            or not isinstance(claim.get("dataset_name"), str)
            or not claim["dataset_name"].strip()
            or not isinstance(claim.get("package_id"), str)
            or not claim["package_id"].strip()
            or claim["package_id"] in packages
            or not isinstance(claim.get("record_count"), int)
            or isinstance(claim.get("record_count"), bool)
            or claim["record_count"] < 1
            or claim.get("role")
            not in {"deployment_approval", "flagship", "portability"}
        ):
            raise ValueError("retained signed transaction status is invalid")
        packages.add(claim["package_id"])
        counts.add(claim["record_count"])
    count = len(value)
    noun = "transaction" if count == 1 else "transactions"
    record_text = (
        f", {next(iter(counts))} records each" if len(counts) == 1 and count > 1 else ""
    )
    if count == 1:
        record_text = f", {next(iter(counts))} records"
    return f"Retained ({count} signed {noun}{record_text})"


def render() -> str:
    matrix = load(ROOT / "matrix.json")
    demonstrations = load(ROOT / "demonstrations.json")["profiles"]
    categories = matrix["categories"]
    profiles = matrix["profiles"]
    authoritative_records = load(ROOT / "authoritative" / "cases.json")["records"]
    record_count = len(authoritative_records)
    lines = [
        "<!-- Generated by examples/evaluator-qualification/"
        "render_docs_matrix.py; do not edit by hand. -->",
        "",
    ]
    for category_id, category in categories.items():
        lines.extend(
            [
                f"### {category['display_name']}",
                "",
                "| Upstream evaluator | Pinned version | Executed upstream entry "
                "point | Adapter support | Replay authority | "
                "Retained signed transactions |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        category_profiles = [
            profile for profile in profiles if profile["category"] == category_id
        ]
        for profile in category_profiles:
            profile_id = profile["profile_id"]
            levels = demonstrations[profile_id]
            raw = load(ROOT / "artifacts" / profile_id / "upstream-output.json")
            end_to_end = retained_transactions(levels["retained_signed_transactions"])
            cells = (
                profile["display_name"],
                pinned_version(profile),
                f"`{raw['entrypoint']}`",
                adapter_support(profile),
                (
                    f"Independently replayable ({record_count} shared outputs)"
                    if profile["authority"]["mode"] == "deterministic_per_record"
                    else replay_authority(profile)
                ),
                end_to_end,
            )
            lines.append(
                "| " + " | ".join(escape_cell(str(cell)) for cell in cells) + " |"
            )
        lines.append("")
    return "\n".join(lines)


def updated_document(current: str) -> str:
    if current.count(START) != 1 or current.count(END) != 1:
        raise ValueError("documentation must contain one generated matrix block")
    prefix, remainder = current.split(START, 1)
    _, suffix = remainder.split(END, 1)
    return f"{prefix}{START}\n{render()}{END}{suffix}"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    current = DOCUMENT.read_text(encoding="utf-8")
    expected = updated_document(current)
    if args.write:
        DOCUMENT.write_text(expected, encoding="utf-8")
        return 0
    if current == expected:
        return 0
    print(
        "".join(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(DOCUMENT),
                tofile=f"{DOCUMENT} (generated)",
            )
        ),
        end="",
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
