#!/usr/bin/env python3
"""Render the evaluator documentation matrix from retained manifests."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parents[1]
DOCUMENT = REPO / "docs" / "reference" / "evaluator-qualification.md"
START = "<!-- evaluator-matrix:start -->"
END = "<!-- evaluator-matrix:end -->"


def load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_bytes())
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain an object")
    return value


def pinned_version(profile: dict[str, Any]) -> str:
    package = profile["upstream"]
    lock = (ROOT / profile["lock"]).read_text(encoding="utf-8").strip()
    if "git+" in lock:
        revision = lock.rsplit("@", 1)[-1]
        return f"source revision `{revision[:7]}` (`{package['version']}`)"
    separator = "@" if package["ecosystem"] == "npm" else "=="
    return f"`{package['name']}{separator}{package['version']}`"


def qualification(profile: dict[str, Any]) -> str:
    authority = profile["authority"]
    if authority["mode"] == "deterministic_per_record":
        return "Per-record"
    reason = str(authority["reason"]).replace("_", " ")
    return f"Observation-only: {reason}"


def escape_cell(value: str) -> str:
    return value.replace("|", r"\|").replace("\n", " ")


def render() -> str:
    matrix = load(ROOT / "matrix.json")
    demonstrations = load(ROOT / "demonstrations.json")["profiles"]
    categories = matrix["categories"]
    profiles = matrix["profiles"]
    authoritative_records = load(ROOT / "authoritative" / "cases.json")["records"]
    record_count = len(authoritative_records)
    lines = [
        "<!-- Generated by examples/evaluator-qualification/"
        "render_docs_matrix.py; do not edit by hand. -->",
        "",
    ]
    for category_id, category in categories.items():
        lines.extend(
            [
                f"### {category['display_name']}",
                "",
                "| Upstream evaluator | Pinned version | Executed upstream entry "
                "point | Qualification profile | Authoritative import | "
                "End-to-end transaction |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        category_profiles = [
            profile for profile in profiles if profile["category"] == category_id
        ]
        for profile in category_profiles:
            profile_id = profile["profile_id"]
            levels = demonstrations[profile_id]
            raw = load(ROOT / "artifacts" / profile_id / "upstream-output.json")
            authoritative = (
                f"{record_count} records" if levels["authoritative_import"] else "No"
            )
            end_to_end = (
                "Demonstrated"
                if levels["end_to_end_transaction"]
                else "Not yet demonstrated"
            )
            cells = (
                profile["display_name"],
                pinned_version(profile),
                f"`{raw['entrypoint']}`",
                qualification(profile),
                authoritative,
                end_to_end,
            )
            lines.append(
                "| " + " | ".join(escape_cell(str(cell)) for cell in cells) + " |"
            )
        lines.append("")
    return "\n".join(lines)


def updated_document(current: str) -> str:
    if current.count(START) != 1 or current.count(END) != 1:
        raise ValueError("documentation must contain one generated matrix block")
    prefix, remainder = current.split(START, 1)
    _, suffix = remainder.split(END, 1)
    return f"{prefix}{START}\n{render()}{END}{suffix}"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    current = DOCUMENT.read_text(encoding="utf-8")
    expected = updated_document(current)
    if args.write:
        DOCUMENT.write_text(expected, encoding="utf-8")
        return 0
    if current == expected:
        return 0
    print(
        "".join(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(DOCUMENT),
                tofile=f"{DOCUMENT} (generated)",
            )
        ),
        end="",
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
