from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
EXAMPLE = ROOT / "examples/evaluator-qualification"
SCRIPT = EXAMPLE / "render_docs_matrix.py"


def _module() -> Any:
    spec = importlib.util.spec_from_file_location("evaluator_docs_renderer", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_renderer_loads_controls_and_renders_all_categories(tmp_path: Path) -> None:
    module = _module()
    rendered = module.render()

    matrix = json.loads((EXAMPLE / "matrix.json").read_bytes())
    assert rendered.startswith("<!-- Generated by ")
    assert rendered.count("| Upstream evaluator |") == len(matrix["categories"])
    assert (
        "| Adapter support | Replay authority | Retained signed transaction |"
        in rendered
    )
    for profile in matrix["profiles"]:
        assert profile["display_name"] in rendered

    invalid = tmp_path / "invalid.json"
    invalid.write_text("[]", encoding="utf-8")
    with pytest.raises(ValueError, match="must contain an object"):
        module.load(invalid)


def test_renderer_formats_versions_authority_and_markdown_cells(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = _module()
    pypi = {
        "lock": "locks/example.txt",
        "upstream": {
            "ecosystem": "pypi",
            "name": "example",
            "version": "1.2.3",
        },
    }
    npm = {
        "lock": "locks/example.txt",
        "upstream": {
            "ecosystem": "npm",
            "name": "example",
            "version": "1.2.3",
        },
    }
    source = {
        "lock": "locks/example.txt",
        "upstream": {
            "ecosystem": "pypi",
            "name": "example",
            "version": "1.2.3",
        },
    }
    fake_root = tmp_path
    (fake_root / "locks").mkdir()
    lock = fake_root / "locks/example.txt"
    monkeypatch.setattr(module, "ROOT", fake_root)

    lock.write_text("example==1.2.3\n", encoding="utf-8")
    assert module.pinned_version(pypi) == "`example==1.2.3`"
    assert module.pinned_version(npm) == "`example@1.2.3`"
    lock.write_text("example @ git+https://example.invalid/repo@abcdef1234\n")
    assert "source revision `abcdef1`" in module.pinned_version(source)

    assert (
        module.replay_authority(
            {"authority": {"mode": "deterministic_per_record", "reason": None}}
        )
        == "Independently replayable"
    )
    assert (
        module.replay_authority(
            {"authority": {"mode": "observation_only", "reason": "aggregate_only"}}
        )
        == "Observation-only: aggregate only"
    )
    assert (
        module.adapter_support({"support_status": "maintained_adapter"}) == "Maintained"
    )
    assert module.escape_cell("a|b\nc") == r"a\|b c"


def test_updated_document_requires_exactly_one_generated_block() -> None:
    module = _module()
    with pytest.raises(ValueError, match="one generated matrix block"):
        module.updated_document("missing")
    with pytest.raises(ValueError, match="one generated matrix block"):
        module.updated_document(f"{module.START}{module.START}{module.END}{module.END}")

    current = f"before\n{module.START}\nold\n{module.END}\nafter\n"
    updated = module.updated_document(current)
    assert updated.startswith(f"before\n{module.START}\n<!-- Generated by ")
    assert updated.endswith(f"{module.END}\nafter\n")


def test_main_checks_writes_and_prints_drift(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    module = _module()
    document = tmp_path / "matrix.md"
    current = f"before\n{module.START}\nold\n{module.END}\nafter\n"
    document.write_text(current, encoding="utf-8")
    monkeypatch.setattr(module, "DOCUMENT", document)
    monkeypatch.setattr(module, "render", lambda: "generated\n")

    monkeypatch.setattr(
        module,
        "parse_args",
        lambda: argparse.Namespace(check=True, write=False),
        raising=False,
    )
    monkeypatch.setattr(sys, "argv", [str(SCRIPT), "--check"])
    assert module.main() == 1
    assert "--- " in capsys.readouterr().out

    monkeypatch.setattr(sys, "argv", [str(SCRIPT), "--write"])
    assert module.main() == 0
    assert "generated" in document.read_text(encoding="utf-8")

    monkeypatch.setattr(sys, "argv", [str(SCRIPT), "--check"])
    assert module.main() == 0
