"""Report discovery and scenario classification for pack verification.

The shell-facing verifier keeps command dispatch and pack-control checks in
``verify_pack_checks``.  This module owns the report layout and scenario
classification rules shared by its report-verification modes.
"""

from __future__ import annotations

import sys
from collections.abc import Sequence
from pathlib import Path

try:
    from invarlock.evidence_pack_json import load_json_object
except ImportError:  # pragma: no cover - direct script execution path
    _REPO_SRC = Path(__file__).resolve().parents[3] / "src"
    if str(_REPO_SRC) not in sys.path:
        sys.path.insert(0, str(_REPO_SRC))
    from invarlock.evidence_pack_json import load_json_object


CLASSIFIED_STRICTNESS = {"must_pass", "must_fail", "must_detect", "informational"}


def report_scenario_id(pack_dir: Path, report: Path) -> str | None:
    """Return the scenario identifier encoded by a staged report path."""

    try:
        relative = report.resolve().relative_to((pack_dir / "reports").resolve())
    except ValueError:
        return None
    parts = relative.parts
    if len(parts) == 2:
        scenario = parts[0].strip()
        return scenario or None
    if len(parts) < 3:
        return None
    if parts[1] == "errors" and len(parts) >= 4:
        scenario = parts[2].strip()
        return scenario or None
    scenario = parts[1].strip()
    return scenario or None


def scenario_strictness(scenarios_path: Path, scenario_id: str) -> str | None:
    """Read one declared scenario strictness from canonical strict JSON."""

    payload = load_json_object(
        scenarios_path,
        label=f"JSON input {scenarios_path}",
    )
    scenarios = payload.get("scenarios")
    if not isinstance(scenarios, list):
        return None
    for scenario in scenarios:
        if not isinstance(scenario, dict) or scenario.get("id") != scenario_id:
            continue
        strictness = scenario.get("strictness")
        if isinstance(strictness, str) and strictness:
            return strictness
    return None


def report_expects_verify_failure(pack_dir: Path, report: Path) -> bool:
    """Whether a report is explicitly classified as a verification failure."""

    scenario_id = report_scenario_id(pack_dir, report)
    scenarios_path = pack_dir / "metadata" / "scenarios.json"
    if scenario_id is not None and scenarios_path.is_file():
        strictness = scenario_strictness(scenarios_path, scenario_id)
        if strictness is not None:
            return strictness == "must_fail"
        return False

    if not scenarios_path.is_file() and is_error_injection_report(report):
        return True

    return False


def report_is_informational(pack_dir: Path, report: Path) -> bool:
    """Whether a report may fail verification without failing the pack."""

    scenario_id = report_scenario_id(pack_dir, report)
    scenarios_path = pack_dir / "metadata" / "scenarios.json"
    if scenario_id is None or not scenarios_path.is_file():
        return False
    return scenario_strictness(scenarios_path, scenario_id) == "informational"


def unclassified_reports(pack_dir: Path, reports: Sequence[Path]) -> list[Path]:
    """Return reports absent from the current scenario manifest."""

    scenarios_path = pack_dir / "metadata" / "scenarios.json"
    if not scenarios_path.is_file():
        return list(reports)
    unclassified: list[Path] = []
    for report in reports:
        scenario_id = report_scenario_id(pack_dir, report)
        strictness = (
            scenario_strictness(scenarios_path, scenario_id)
            if scenario_id is not None
            else None
        )
        if strictness not in CLASSIFIED_STRICTNESS:
            unclassified.append(report)
    return unclassified


def is_error_injection_report(report: Path) -> bool:
    """Identify reports generated by the historical error-injection layout."""

    return "errors" in report.parts and report.name == "evaluation.report.json"


def report_counts_as_clean_pass(pack_dir: Path, report: Path) -> bool:
    """Whether a report contributes to the required clean-pass population."""

    return not is_error_injection_report(report) and not report_expects_verify_failure(
        pack_dir, report
    )


def report_paths(pack_dir: Path) -> list[Path]:
    """Find staged evaluation reports in deterministic order."""

    reports_root = pack_dir / "reports"
    if not reports_root.is_dir():
        return []
    return sorted(reports_root.rglob("evaluation.report.json"))
