#!/usr/bin/env python3
"""
Enforce per-file coverage thresholds.

Expects a ``coverage.xml`` report generated by ``coverage.py`` / ``pytest-cov``.
"""

from __future__ import annotations

import argparse
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

# Explicit per-file overrides. Values are branch floors unless branch-rate is
# unavailable, in which case line-rate is used as a fallback. These take
# precedence over the global/core floors below and encode the split-aware
# coverage policy for shells, pure helpers, and tensor/mutation helpers.
THRESHOLDS = {
    # Evaluation & reporting
    "src/invarlock/eval/data.py": 0.75,
    "src/invarlock/eval/bootstrap.py": 1.00,
    "src/invarlock/eval/bench_regression.py": 1.00,
    "src/invarlock/eval/probes/fft.py": 1.00,
    "src/invarlock/eval/probes/mi.py": 0.90,
    "src/invarlock/eval/probes/post_attention.py": 0.90,
    "src/invarlock/eval/providers/base.py": 1.00,
    "src/invarlock/eval/providers/seq2seq.py": 0.90,
    "src/invarlock/eval/metrics.py": 0.90,
    # Guard-effect benchmark harness (Step 14) + primary metric core
    "src/invarlock/eval/bench.py": 0.90,
    "src/invarlock/eval/bench_policy.py": 0.95,
    "src/invarlock/eval/bench_runner.py": 0.75,
    "src/invarlock/eval/primary_metric.py": 0.90,
    "src/invarlock/eval/tail_stats.py": 0.95,
    "src/invarlock/eval/tasks/classification.py": 1.00,
    "src/invarlock/eval/tasks/qa.py": 1.00,
    "src/invarlock/eval/tasks/text_generation.py": 0.90,
    # Calibration (release artifacts / tier updates)
    "src/invarlock/calibration/spectral_null.py": 0.90,
    "src/invarlock/calibration/variance_ve.py": 0.90,
    # Reporting
    "src/invarlock/reporting/report_builder.py": 0.90,
    "src/invarlock/reporting/report.py": 0.90,
    "src/invarlock/reporting/validate.py": 0.95,
    # Reporting types
    "src/invarlock/reporting/report_types.py": 1.00,
    "src/invarlock/reporting/dataset_hashing.py": 0.90,
    "src/invarlock/reporting/guards_analysis.py": 0.90,
    "src/invarlock/reporting/primary_metric_utils.py": 0.90,
    "src/invarlock/reporting/utils.py": 1.00,
    # Shell modules: lifecycle/orchestration shells should stay branch-complete.
    "src/invarlock/core/runner.py": 1.00,
    "src/invarlock/guards/variance.py": 1.00,
    "src/invarlock/guards/spectral.py": 1.00,
    # Pure contract / result / policy / selection helpers.
    "src/invarlock/reporting/report_schema.py": 1.00,
    "src/invarlock/public_contracts.py": 1.00,
    "src/invarlock/policy_pack.py": 1.00,
    # Advanced proof-pack packaging/inspection coverage now exercises the
    # command shell branch-completely; keep the command surface held there.
    "src/invarlock/proof_pack.py": 1.00,
    "src/invarlock/reporting/evidence.py": 1.00,
    "src/invarlock/reporting/verify_output.py": 1.00,
    "src/invarlock/cli/commands/policy.py": 1.00,
    "src/invarlock/cli/commands/proof_pack.py": 1.00,
    "src/invarlock/core/runner_lifecycle.py": 1.00,
    "src/invarlock/core/runner_pairing.py": 1.00,
    "src/invarlock/core/runner_services.py": 1.00,
    "src/invarlock/guards/variance_policy.py": 1.00,
    "src/invarlock/guards/variance_results.py": 1.00,
    "src/invarlock/guards/spectral_policy.py": 1.00,
    "src/invarlock/guards/spectral_results.py": 1.00,
    "src/invarlock/guards/spectral_selection.py": 1.00,
    "src/invarlock/guards/spectral_analysis.py": 1.00,
    # Numerical / mutation / tensor-processing helpers.
    "src/invarlock/core/runner_context.py": 0.95,
    "src/invarlock/core/runner_eval_phase.py": 0.95,
    "src/invarlock/core/runner_latency.py": 0.95,
    "src/invarlock/core/runner_eval_windows.py": 0.95,
    "src/invarlock/guards/variance_batching.py": 1.00,
    "src/invarlock/guards/variance_evaluation.py": 0.95,
    "src/invarlock/guards/variance_prepare.py": 1.00,
    "src/invarlock/guards/variance_ops.py": 0.95,
    "src/invarlock/guards/variance_scaling.py": 0.95,
    "src/invarlock/guards/invariants.py": 0.90,
    "src/invarlock/guards/spectral_control.py": 0.95,
    "src/invarlock/guards/spectral_measurement.py": 0.95,
    "src/invarlock/guards/rmt.py": 0.90,
    "src/invarlock/guards/policies.py": 0.95,
    # Core orchestration & runtime
    "src/invarlock/core/registry.py": 1.00,
    "src/invarlock/core/bootstrap.py": 0.95,
    "src/invarlock/core/contracts.py": 0.95,
    "src/invarlock/core/auto_tuning.py": 0.95,
    # Newly added core modules to critical surface
    "src/invarlock/core/checkpoint.py": 0.90,
    "src/invarlock/core/api.py": 1.00,
    "src/invarlock/core/retry.py": 0.95,
    "src/invarlock/core/types.py": 0.90,
    "src/invarlock/core/doctor_findings.py": 0.95,
    "src/invarlock/core/evaluate_plan.py": 0.95,
    "src/invarlock/core/runtime_manifest_verify.py": 0.90,
    # CLI commands
    "src/invarlock/cli/_json.py": 1.00,
    # Simplified public-core CLI surfaces have dedicated branch-focused tests;
    # keep the hero commands above the default 90% floor.
    "src/invarlock/cli/app.py": 1.00,
    "src/invarlock/core/config_runtime.py": 0.95,
    "src/invarlock/cli/commands/evaluate.py": 0.95,
    "src/invarlock/cli/commands/report.py": 0.95,
    "src/invarlock/cli/commands/run.py": 0.95,
    "src/invarlock/cli/commands/verify.py": 0.95,
    "src/invarlock/cli/commands/calibrate.py": 0.90,
    "src/invarlock/reporting/report_files.py": 0.95,
    "src/invarlock/reporting/verify_checks.py": 0.95,
    "src/invarlock/reporting/verify_contract.py": 0.95,
    "src/invarlock/runtime_verify.py": 1.00,
    "src/invarlock/runtime_security.py": 0.95,
    # PR-4 split modules
    "src/invarlock/cli/run_artifacts.py": 1.00,
    "src/invarlock/cli/run_config.py": 1.00,
    "src/invarlock/cli/run_overhead.py": 1.00,
    "src/invarlock/cli/run_pairing.py": 0.90,
    "src/invarlock/cli/run_policy.py": 1.00,
    "src/invarlock/reporting/run_metric_utils.py": 1.00,
    # CLI determinism preset (CI/Release provenance)
    "src/invarlock/cli/determinism.py": 0.95,
    # Core events logger
    "src/invarlock/core/events.py": 0.90,
    # PR-5 split modules
    "src/invarlock/core/runner_eval_metrics.py": 0.90,
    "src/invarlock/core/runner_finalize.py": 0.90,
    "src/invarlock/core/runner_guards.py": 0.90,
    "src/invarlock/reporting/report_overhead.py": 0.95,
    "src/invarlock/reporting/report_policy.py": 0.95,
    "src/invarlock/reporting/report_provenance.py": 0.95,
    "src/invarlock/reporting/report_validation.py": 0.95,
}

# Default floors (applied only to core classification; non-core modules are not
# globally enforced unless explicitly listed in THRESHOLDS)
CORE_FLOOR_DEFAULT = 0.90
DEFAULT_FLOOR_DEFAULT = 0.90

# Core module classification: files matching any of these prefixes are treated
# as part of the critical surface and must meet the core floor (unless an
# explicit override in THRESHOLDS is present).
# NOTE: Keep this aligned with CONTRIBUTING.md "Coverage Policy" and update
# incrementally as the surface evolves.
CORE_PREFIXES = (
    # Core orchestration & runtime
    "src/invarlock/core/",
    # Guards (safety mechanisms)
    "src/invarlock/guards/",
)

# Individual core files outside of the broad prefixes
CORE_FILES = (
    # Evaluation & reporting (key entry points)
    "src/invarlock/eval/data.py",
    "src/invarlock/eval/bootstrap.py",
    "src/invarlock/eval/bench_regression.py",
    "src/invarlock/eval/probes/fft.py",
    "src/invarlock/eval/probes/mi.py",
    "src/invarlock/eval/probes/post_attention.py",
    "src/invarlock/eval/providers/base.py",
    "src/invarlock/eval/providers/seq2seq.py",
    "src/invarlock/eval/metrics.py",
    "src/invarlock/eval/bench.py",
    "src/invarlock/eval/bench_policy.py",
    "src/invarlock/eval/bench_runner.py",
    "src/invarlock/eval/primary_metric.py",
    "src/invarlock/eval/tail_stats.py",
    "src/invarlock/eval/tasks/classification.py",
    "src/invarlock/eval/tasks/qa.py",
    "src/invarlock/eval/tasks/text_generation.py",
    "src/invarlock/calibration/spectral_null.py",
    "src/invarlock/calibration/variance_ve.py",
    "src/invarlock/reporting/report.py",
    "src/invarlock/reporting/validate.py",
    "src/invarlock/reporting/report_types.py",
    "src/invarlock/reporting/dataset_hashing.py",
    "src/invarlock/reporting/report_schema.py",
    "src/invarlock/reporting/guards_analysis.py",
    "src/invarlock/reporting/primary_metric_utils.py",
    "src/invarlock/reporting/utils.py",
    # Report builder is part of the reporting surface but has an explicit
    # transitional override below until tests mature
    "src/invarlock/reporting/report_builder.py",
    # Critical CLI commands
    "src/invarlock/cli/commands/run.py",
    "src/invarlock/cli/commands/evaluate.py",
    "src/invarlock/cli/commands/report.py",
    "src/invarlock/cli/commands/verify.py",
    "src/invarlock/cli/commands/calibrate.py",
    "src/invarlock/cli/commands/policy.py",
    "src/invarlock/reporting/report_files.py",
    "src/invarlock/reporting/verify_checks.py",
    "src/invarlock/reporting/verify_contract.py",
    "src/invarlock/reporting/verify_output.py",
    "src/invarlock/reporting/evidence.py",
    "src/invarlock/cli/determinism.py",
    "src/invarlock/core/config_runtime.py",
    "src/invarlock/cli/_json.py",
    "src/invarlock/cli/app.py",
    "src/invarlock/core/doctor_findings.py",
    "src/invarlock/core/evaluate_plan.py",
    # Public contract helpers
    "src/invarlock/public_contracts.py",
    "src/invarlock/policy_pack.py",
    "src/invarlock/proof_pack.py",
    "src/invarlock/runtime_verify.py",
    "src/invarlock/cli/commands/proof_pack.py",
    "src/invarlock/runtime_security.py",
)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Enforce per-file coverage floors")
    parser.add_argument(
        "--coverage",
        default="coverage.xml",
        help="Path to coverage XML report (default: coverage.xml)",
    )
    parser.add_argument(
        "--json",
        dest="json_path",
        help="Optional path to write results as JSON",
    )
    parser.add_argument(
        "--core-floor",
        type=float,
        default=CORE_FLOOR_DEFAULT,
        help=f"Branch coverage floor for core modules (default: {CORE_FLOOR_DEFAULT:.0%})",
    )
    parser.add_argument(
        "--default-floor",
        type=float,
        default=DEFAULT_FLOOR_DEFAULT,
        help=(
            f"Branch coverage floor for non-core modules (default: {DEFAULT_FLOOR_DEFAULT:.0%}). "
            "Note: non-core floors are only applied for files explicitly listed in THRESHOLDS."
        ),
    )
    return parser.parse_args()


def _load_coverage_xml(path: Path) -> ET.Element:
    if not path.exists():
        raise FileNotFoundError(f"Coverage report not found: {path}")
    return ET.parse(path).getroot()


def _collect_branch_rates(root: ET.Element) -> dict[str, float]:
    """Return mapping of normalized file path → branch rate (fallback to line rate).

    Coverage.py emits class-level attributes like 'branch-rate' and 'line-rate'.
    We prefer branch-rate to enforce branch coverage floors, and fall back to
    line-rate if branch-rate is unavailable for a file.
    """

    # Order matters when coverage.xml reports ambiguous bare filenames (e.g.,
    # "bootstrap.py"). Prefer core/reporting over eval so we map to the
    # critical surfaces used in thresholds.
    search_roots = [
        Path("src/invarlock/core"),
        Path("src/invarlock/reporting"),
        Path("src/invarlock/cli"),
        Path("src/invarlock/calibration"),
        Path("src/invarlock/guards"),
        Path("src/invarlock/eval"),
        Path("scripts"),
    ]

    def _normalize_project_path(path: Path) -> str | None:
        """Return project-relative path starting at src/ or scripts/.

        Coverage XML often emits absolute paths. We want stable keys like
        "src/invarlock/core/runner.py" that match THRESHOLDS. This helper trims any
        absolute prefix up to the first occurrence of "src/" or "scripts/".
        """
        try:
            p = path.resolve()
        except Exception:
            p = path

        # If the path already looks project-relative, keep it
        text = p.as_posix()
        for anchor in ("src/", "scripts/"):
            idx = text.find(anchor)
            if idx != -1:
                return text[idx:]
        # Handle coverage XML that emits package-relative paths like
        # "invarlock/cli/commands/run.py" without the leading "src/" prefix.
        # In that case, restore the expected project-relative prefix.
        if text.startswith("invarlock/"):
            return f"src/{text}"
        # Fallback: if it exists under CWD, try to relativize
        try:
            rel = p.relative_to(Path.cwd())
            return rel.as_posix()
        except Exception:
            return None

    def resolve_path(filename: str) -> str | None:
        # Fast-path: coverage emits package-relative paths like "invarlock/..."
        # Map these directly to project-relative under src/.
        if filename.startswith("invarlock/"):
            return f"src/{filename}"
        # Coverage XML may emit bare basenames for multiple modules (e.g., both
        # src/invarlock/core/bootstrap.py and src/invarlock/eval/bootstrap.py).
        # In those cases, mapping is ambiguous and can mis-attribute rates.
        if filename in {"bootstrap.py"} and "/" not in filename:
            return None
        candidate = Path(filename)
        # Try normalizing absolute paths first
        if candidate.exists():
            norm = _normalize_project_path(candidate)
            if norm:
                return norm
        # Try joining against known roots
        for root_path in search_roots:
            resolved = root_path / filename
            if resolved.exists():
                norm = _normalize_project_path(resolved)
                if norm:
                    return norm
        return None

    rates: dict[str, float] = {}
    for class_node in root.findall("./packages/package/classes/class"):
        filename = class_node.attrib.get("filename")
        if not filename:
            continue
        # Prefer branch-rate; fallback to line-rate
        rate_str = class_node.attrib.get("branch-rate") or class_node.attrib.get(
            "line-rate"
        )
        try:
            rate = float(rate_str or 0.0)
        except (TypeError, ValueError):
            rate = 0.0
        # Normalize path; some coverage outputs are already project-relative
        # (e.g., "invarlock/cli/commands/run.py")
        norm = resolve_path(filename.replace("\\", "/"))
        if not norm:
            continue
        # Keep the highest rate seen if tool emits duplicates per class
        rates[norm] = max(rate, rates.get(norm, 0.0))
    return rates


def _write_json(
    json_path: Path,
    records: list[dict[str, Any]],
    status: str,
    *,
    configured_threshold_files: int,
    evaluated_files: int,
    missing_threshold_files: list[str],
    measured_threshold_files: int,
) -> None:
    payload = {
        "status": status,
        "files": records,
        "configured_threshold_files": configured_threshold_files,
        "evaluated_files": evaluated_files,
        "measured_threshold_files": measured_threshold_files,
        "missing_threshold_files": missing_threshold_files,
    }
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def main() -> int:
    args = _parse_args()
    report_path = Path(args.coverage)
    root = _load_coverage_xml(report_path)
    rates = _collect_branch_rates(root)

    failures: list[str] = []
    records: list[dict[str, Any]] = []

    def _is_core(path: str) -> bool:
        return path in CORE_FILES or any(path.startswith(p) for p in CORE_PREFIXES)

    # Build required floors for core classification only; non-core modules are
    # not globally enforced to avoid over-scoping. Explicit overrides (below)
    # extend this set.
    required: dict[str, float] = {}
    for rel_path in rates.keys():
        if _is_core(rel_path):
            required[rel_path] = args.core_floor

    # Apply explicit overrides (can be lower or higher than the base floor).
    # Only enforce overrides for files that appear in the current report.
    for rel_path, floor in THRESHOLDS.items():
        if rel_path in rates:
            required[rel_path] = floor

    missing_threshold_files = sorted(set(THRESHOLDS) - set(rates))
    measured_threshold_files = len(THRESHOLDS) - len(missing_threshold_files)

    # Evaluate all known files with a required floor
    for rel_path, floor in sorted(required.items()):
        rate = rates.get(rel_path)
        record = {
            "path": rel_path,
            "threshold": floor,
            "coverage": rate,
            "core": _is_core(rel_path),
        }
        records.append(record)
        if rate is None:
            failures.append(f"{rel_path}: no coverage data present")
            continue
        if rate + 1e-9 < floor:
            failures.append(
                f"{rel_path}: coverage {rate:.3%} below required {floor:.0%}"
            )

    if args.json_path:
        _write_json(
            Path(args.json_path),
            records,
            "fail" if failures else "ok",
            configured_threshold_files=len(THRESHOLDS),
            evaluated_files=len(records),
            missing_threshold_files=missing_threshold_files,
            measured_threshold_files=measured_threshold_files,
        )

    if failures:
        for failure in failures:
            print(f"Coverage threshold not met: {failure}", file=sys.stderr)
        return 1

    for rel_path, threshold in THRESHOLDS.items():
        rate = rates.get(rel_path)
        if rate is not None:
            print(f"{rel_path}: {rate:.2%} (branch threshold {threshold:.0%})")
            if threshold < 0.85:
                print(
                    "  note: phased coverage floor – ratchet upward when touching this file"
                )

    summary = (
        f"Coverage OK: {measured_threshold_files}/{len(THRESHOLDS)} threshold-listed files had coverage data "
        "and met per-file thresholds. "
    )
    if missing_threshold_files:
        summary += (
            f"{len(missing_threshold_files)} threshold-listed files were absent from the "
            "coverage report. "
        )
    summary += "Project floor enforced via pytest."
    print(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
