"""Top-level pipeline coordination for config-driven run orchestration."""

from __future__ import annotations

from typing import Any

from invarlock.core.run_orchestrator_execute_outcome import _build_outcome_result
from invarlock.core.run_orchestrator_types import (
    RunExecutionRequest,
    RunExecutionResult,
    RunExecutionServices,
)
from invarlock.core.run_retry_policy import (
    build_restore_failure_attempt_summary,
    decide_failed_retry_transition,
    record_retry_attempt,
)


def _execute_run_pipeline_steps(
    *,
    request: RunExecutionRequest,
    services: RunExecutionServices,
    profile_normalized: str,
    collect_timings: bool,
    total_start: float | None,
    timings: dict[str, float],
    emit: Any,
    emit_diagnostic: Any,
    emit_guard_overhead_summary: Any,
    emit_retry_summary: Any,
    emit_transition: Any,
    halt: Any,
    fail_run: Any,
    record_timed_step: Any,
    cfg_value: Any,
    optional_torch: Any,
    require_torch: Any,
    build_timing_summary_payload_fn: Any,
    resolve_retry_validation_transition_fn: Any,
    config_value_exceptions: tuple[type[BaseException], ...],
    numeric_exceptions: tuple[type[BaseException], ...],
    optional_runtime_exceptions: tuple[type[BaseException], ...],
) -> tuple[RunExecutionResult, Any | None]:
    from invarlock.core.api import RunConfig
    from invarlock.core.registry import get_registry
    from invarlock.core.run_orchestrator_execute_attempts import _execute_attempt_loop
    from invarlock.core.run_orchestrator_execute_dataset import _load_dataset_state
    from invarlock.core.run_orchestrator_execute_environment import (
        _prepare_run_environment,
    )
    from invarlock.core.run_orchestrator_execute_execution import (
        _prepare_execution_state,
        _resolve_run_components,
    )
    from invarlock.core.runner import CoreRunner

    env_state = _prepare_run_environment(
        config=request.config,
        profile=request.profile,
        profile_normalized=profile_normalized,
        edit=request.edit,
        tier=request.tier,
        probes=request.probes,
        device=request.device,
        out=request.out or "",
        until_pass=bool(request.until_pass),
        max_attempts=int(request.max_attempts),
        timeout=request.timeout,
        baseline=request.baseline,
        determinism_mode=request.determinism_mode,
        determinism_warn_only=bool(request.determinism_warn_only),
        prepare_config_for_run_fn=services.prepare_config_for_run,
        detect_model_profile_fn=services.detect_model_profile,
        resolve_device_and_output_fn=services.resolve_device_and_output,
        init_retry_controller_fn=services.init_retry_controller,
        load_baseline_pairing_evidence_fn=services.load_baseline_pairing_evidence,
        safe_int_fn=services.safe_int,
        optional_torch=optional_torch,
        require_torch=require_torch,
        cfg_value=cfg_value,
        emit=emit,
        emit_diagnostic=emit_diagnostic,
        config_value_exceptions=config_value_exceptions,
        numeric_exceptions=numeric_exceptions,
        optional_runtime_exceptions=optional_runtime_exceptions,
    )
    component_state = _resolve_run_components(
        cfg=env_state.cfg,
        profile=request.profile,
        eval_device_override=request.eval_device_override,
        pairing_schedule=env_state.pairing_schedule,
        seed_bundle=env_state.seed_bundle,
        run_id=env_state.run_id,
        baseline_report_data=env_state.baseline_report_data,
        model_profile=env_state.model_profile,
        resolved_loss_type=env_state.resolved_loss_type,
        tiny_relax_enabled=bool(request.tiny_relax_enabled),
        resolved_device=env_state.resolved_device,
        eval_section=env_state.eval_section,
        run_dir=env_state.run_dir,
        get_registry_fn=get_registry,
        run_config_type=RunConfig,
        to_serialisable_dict_fn=services.to_serialisable_dict,
        cfg_value=cfg_value,
        emit=emit,
        emit_diagnostic=emit_diagnostic,
        halt=halt,
    )
    dataset_state = _load_dataset_state(
        cfg=env_state.cfg,
        model_profile=env_state.model_profile,
        resolved_device=env_state.resolved_device,
        profile=request.profile,
        profile_normalized=profile_normalized,
        requested_preview=env_state.requested_preview,
        requested_final=env_state.requested_final,
        effective_preview=env_state.effective_preview,
        effective_final=env_state.effective_final,
        use_mlm=env_state.use_mlm,
        mask_prob=env_state.mask_prob,
        mask_seed=env_state.mask_seed,
        random_token_prob=env_state.random_token_prob,
        original_token_prob=env_state.original_token_prob,
        resolved_loss_type=env_state.resolved_loss_type,
        tier=request.tier,
        baseline_report_data=env_state.baseline_report_data,
        tokenizer=env_state.tokenizer,
        tokenizer_hash=env_state.tokenizer_hash,
        resolved_split=env_state.resolved_split,
        pairing_schedule=env_state.pairing_schedule,
        collect_timings=collect_timings,
        timings=timings,
        run_context=component_state.run_context,
        materialize_run_dataset_fn=services.materialize_run_dataset,
        validate_and_harvest_baseline_schedule_fn=(
            services.validate_and_harvest_baseline_schedule
        ),
        materialize_baseline_pairing_schedule_fn=(
            services.materialize_baseline_pairing_schedule
        ),
        resolve_tokenizer_fn=services.resolve_tokenizer,
        build_provider_dataset_plan_fn=services.build_provider_dataset_plan,
        emit=emit,
        emit_transition=emit_transition,
        fail_run=fail_run,
    )
    execution_state = _prepare_execution_state(
        cfg=env_state.cfg,
        model_profile=env_state.model_profile,
        profile_normalized=profile_normalized,
        resolved_device=env_state.resolved_device,
        run_dir=env_state.run_dir,
        run_id=env_state.run_id,
        adapter=component_state.adapter,
        edit_op=component_state.edit_op,
        guards=component_state.guards,
        prefer_local_files_only=request.prefer_local_files_only,
        skip_overhead=env_state.skip_overhead,
        skip_overhead_source=env_state.skip_overhead_source,
        direct_reuse_loaded_model=env_state.direct_reuse_loaded_model,
        emitted_skip_overhead_warning=env_state.emitted_skip_overhead_warning,
        retry_controller=env_state.retry_controller,
        cfg_value=cfg_value,
        emit=emit,
        emit_transition=emit_transition,
        record_timed_step=record_timed_step,
        load_model_with_cfg_fn=services.load_model_with_cfg,
        build_snapshot_execution_plan_fn=services.build_snapshot_execution_plan,
        resolve_snapshot_config_fn=services.resolve_snapshot_config,
        resolve_snapshot_retry_transition_fn=services.resolve_snapshot_retry_transition,
        free_model_memory_fn=services.free_model_memory,
        core_runner_type=CoreRunner,
        optional_runtime_exceptions=optional_runtime_exceptions,
    )
    attempt_decision = _execute_attempt_loop(
        execution_state=execution_state,
        cfg=env_state.cfg,
        adapter=component_state.adapter,
        edit_op=component_state.edit_op,
        guards=component_state.guards,
        run_config=component_state.run_config,
        calibration_data=dataset_state.calibration_data,
        preview_count=dataset_state.preview_count,
        final_count=dataset_state.final_count,
        resolved_device=env_state.resolved_device,
        profile_normalized=profile_normalized,
        guard_overhead_threshold=component_state.guard_overhead_threshold,
        skip_overhead=env_state.skip_overhead,
        skip_overhead_source=env_state.skip_overhead_source,
        measure_guard_overhead=env_state.measure_guard_overhead,
        resolved_loss_type=env_state.resolved_loss_type,
        prefer_local_files_only=request.prefer_local_files_only,
        retry_controller=env_state.retry_controller,
        max_attempts=int(request.max_attempts),
        seed_bundle=env_state.seed_bundle,
        seed_value=env_state.seed_value,
        build_restore_failure_attempt_summary_fn=build_restore_failure_attempt_summary,
        decide_failed_retry_transition_fn=decide_failed_retry_transition,
        free_model_memory_fn=services.free_model_memory,
        adjust_edit_params_fn=services.adjust_edit_params,
        run_bare_control_fn=services.run_bare_control,
        execute_guarded_run_fn=services.execute_guarded_run,
        snapshot_restore_failed_type=services.SnapshotRestoreFailed,
        assemble_run_report_fn=services.assemble_run_report,
        persist_run_report_outputs_fn=services.persist_run_report_outputs,
        validate_retry_evaluation_report_fn=services.validate_retry_evaluation_report,
        resolve_retry_validation_transition_fn=resolve_retry_validation_transition_fn,
        record_retry_attempt_fn=record_retry_attempt,
        emit=emit,
        emit_diagnostic=emit_diagnostic,
        emit_guard_overhead_summary=emit_guard_overhead_summary,
        emit_transition=emit_transition,
        halt=halt,
        fail_run=fail_run,
        record_timed_step=record_timed_step,
        timings=timings,
        profile=request.profile,
        baseline=request.baseline,
        edit_label=request.edit_label,
        metric_kind=request.metric_kind,
        export_model_requested=bool(request.export_model_requested),
        export_dir_override=request.export_dir,
        telemetry=bool(request.telemetry),
        tokenizer=dataset_state.tokenizer,
        tokenizer_hash=dataset_state.tokenizer_hash,
        resolved_split=dataset_state.resolved_split,
        effective_preview=dataset_state.effective_preview,
        effective_final=dataset_state.effective_final,
        preview_records=dataset_state.preview_records,
        final_records=dataset_state.final_records,
        preview_mask_counts=dataset_state.preview_mask_counts,
        final_mask_counts=dataset_state.final_mask_counts,
        use_mlm=env_state.use_mlm,
        used_fallback_split=dataset_state.used_fallback_split,
        baseline_report_data=env_state.baseline_report_data,
        window_plan=dataset_state.window_plan,
        model_profile=env_state.model_profile,
        determinism_meta=env_state.determinism_meta,
        pm_acceptance_range=component_state.pm_acceptance_range,
        pm_drift_band=component_state.pm_drift_band,
        run_dir=env_state.run_dir,
        cfg_value=cfg_value,
        optional_runtime_exceptions=optional_runtime_exceptions,
    )
    emit_retry_summary(env_state.retry_controller)
    return (
        _build_outcome_result(
            capture_timings=bool(request.capture_timings),
            total_start=total_start,
            timings=attempt_decision.timings,
            report=attempt_decision.report,
            report_path_out=attempt_decision.report_path_out,
            build_timing_summary_payload_fn=build_timing_summary_payload_fn,
        ),
        execution_state.snapshot_tmpdir,
    )
