"""Typed run orchestration public facade for config-driven run commands."""

from __future__ import annotations

# Public typed event surface retained at the owner boundary:
# class RunExecutionEvent
# class RunLifecycleEvent
# class RunDiagnosticEvent
# class RunContextEvent
# class RunAggregateEvent
# class RunFailureEvent
# class RunPrimaryMetricSummaryEvent
from invarlock.core.run_orchestrator_execute import (
    execute_run_request_impl as execute_run_request,
)
from invarlock.core.run_orchestrator_types import (
    RunAdapterSelectedEvent,
    RunAttemptStartedEvent,
    RunAutoTuneAdjustmentEvent,
    RunBaselineScheduleLoadedEvent,
    RunCalibrationBatchSizesDebugEvent,
    RunCleanupStatusEvent,
    RunConfigLoadedEvent,
    RunConfigLoadingEvent,
    RunDatasetLoadingEvent,
    RunDeterministicSeedsEvent,
    RunDeviceResolvedEvent,
    RunDiagnosticEvent,
    RunEditSelectedEvent,
    RunEvaluationReportFailedEvent,
    RunEvaluationReportPassedEvent,
    RunEvaluationReportStartedEvent,
    RunExecutePipelineEvent,
    RunExecutionEvent,
    RunExecutionFailure,
    RunExecutionObserver,
    RunExecutionOutcome,
    RunExecutionRequest,
    RunExecutionResult,
    RunExecutionServices,
    RunFailureEvent,
    RunGuardChainResolvedEvent,
    RunGuardOverheadSummaryEvent,
    RunLoadModelOnceEvent,
    RunMaskedTokensDebugEvent,
    RunOutputDirectoryReadyEvent,
    RunPipelineStartedEvent,
    RunPreviewLabelsDebugEvent,
    RunPrimaryMetricSummaryEvent,
    RunRetryAttemptStartedEvent,
    RunRetryExhaustedEvent,
    RunRetrySummaryEvent,
    RunRetryValidationErrorEvent,
    RunSnapshotModeEvent,
    RunTelemetryFailedEvent,
    RunTelemetrySavedEvent,
    TimingSummaryPayload,
    _RunExecutionHalt,
)

__all__ = [
    "RunAdapterSelectedEvent",
    "RunAttemptStartedEvent",
    "RunAutoTuneAdjustmentEvent",
    "RunBaselineScheduleLoadedEvent",
    "RunCalibrationBatchSizesDebugEvent",
    "RunCleanupStatusEvent",
    "RunConfigLoadedEvent",
    "RunConfigLoadingEvent",
    "RunDatasetLoadingEvent",
    "RunDeterministicSeedsEvent",
    "RunDeviceResolvedEvent",
    "RunDiagnosticEvent",
    "RunEditSelectedEvent",
    "RunEvaluationReportFailedEvent",
    "RunEvaluationReportPassedEvent",
    "RunEvaluationReportStartedEvent",
    "RunExecutePipelineEvent",
    "RunExecutionEvent",
    "RunExecutionFailure",
    "RunExecutionObserver",
    "RunExecutionOutcome",
    "RunExecutionRequest",
    "RunExecutionResult",
    "RunExecutionServices",
    "RunFailureEvent",
    "RunGuardChainResolvedEvent",
    "RunGuardOverheadSummaryEvent",
    "RunLoadModelOnceEvent",
    "RunMaskedTokensDebugEvent",
    "RunOutputDirectoryReadyEvent",
    "RunPipelineStartedEvent",
    "RunPreviewLabelsDebugEvent",
    "RunPrimaryMetricSummaryEvent",
    "RunRetryAttemptStartedEvent",
    "RunRetryExhaustedEvent",
    "RunRetrySummaryEvent",
    "RunRetryValidationErrorEvent",
    "RunSnapshotModeEvent",
    "RunTelemetryFailedEvent",
    "RunTelemetrySavedEvent",
    "TimingSummaryPayload",
    "_RunExecutionHalt",
    "execute_run_request",
]
