from __future__ import annotations

import hashlib
import json
import re
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn

try:
    from .edit_metadata_contract import (
        ALLOWED_ARTIFACT_CLASSES,
        DELTA_AVAILABILITY_VALUES,
        DEPLOYABLE_OPTIMIZED_SUBJECT,
        EDIT_IMPACT_SCENARIO_TYPES,
        EDIT_METADATA_SCHEMA,
        EDIT_SEMANTICS_DEPLOYABLE,
        EDIT_SEMANTICS_EXTERNAL_SUBJECT,
        EDIT_TOPOLOGY_ARTIFACT_KINDS,
        EVIDENCE_ONLY_PACK,
        FAULT_INJECTION_FIXTURE,
        PRIVACY_SENSITIVITY_VALUES,
        SYNTHETIC_DENSE_UPDATE,
        SYNTHETIC_LOWRANK_DELTA,
        VALIDATION_SUBJECT_CHECKPOINT,
        edit_metadata_coverage_errors,
        is_unverifiable_generated_edit_type,
        storage_format_for_edit,
    )
    from .edit_metadata_contract import (
        validate_edit_metadata as _validate_edit_metadata_contract,
    )
    from .transformation_contract import (
        TransformationContractError,
        canonical_transformation_spec,
        validate_transformation_scope,
    )
except ImportError:  # pragma: no cover - direct script-path loading in tests
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from edit_metadata_contract import (
        ALLOWED_ARTIFACT_CLASSES,
        DELTA_AVAILABILITY_VALUES,
        DEPLOYABLE_OPTIMIZED_SUBJECT,
        EDIT_IMPACT_SCENARIO_TYPES,
        EDIT_METADATA_SCHEMA,
        EDIT_SEMANTICS_DEPLOYABLE,
        EDIT_SEMANTICS_EXTERNAL_SUBJECT,
        EDIT_TOPOLOGY_ARTIFACT_KINDS,
        EVIDENCE_ONLY_PACK,
        FAULT_INJECTION_FIXTURE,
        PRIVACY_SENSITIVITY_VALUES,
        SYNTHETIC_DENSE_UPDATE,
        SYNTHETIC_LOWRANK_DELTA,
        VALIDATION_SUBJECT_CHECKPOINT,
        edit_metadata_coverage_errors,
        is_unverifiable_generated_edit_type,
        storage_format_for_edit,
    )
    from edit_metadata_contract import (
        validate_edit_metadata as _validate_edit_metadata_contract,
    )
    from transformation_contract import (
        TransformationContractError,
        canonical_transformation_spec,
        validate_transformation_scope,
    )

_COERCE_ERRORS = (TypeError, ValueError, OverflowError)
REAL_TRAINING_EDIT_MIGRATIONS: dict[str, tuple[str, str]] = {
    "lora_merge": (
        "synthetic_lowrank_delta",
        "the real PEFT/LoRA integration or training campaign",
    ),
    "fine_tune": (
        "synthetic_dense_update",
        "the real fine-tune integration or training campaign",
    ),
}
_VERIFIER_GRADE_TRANSFORMATION_TYPES = frozenset(
    {"quant_rtn", SYNTHETIC_LOWRANK_DELTA, SYNTHETIC_DENSE_UPDATE}
)
_GENERATED_TRANSFORMATION_DIRECTORY_SCHEMA = (
    "invarlock/generated-transformation-directory-v1"
)
_DIRECTORY_VERSION_RE = re.compile(r"[a-z0-9][a-z0-9._-]*\Z")


def real_training_edit_migration_message(edit_type: str) -> str | None:
    """Return migration guidance for real edits rejected by generated transforms."""

    normalized = edit_type.strip().lower().replace("-", "_")
    migration = REAL_TRAINING_EDIT_MIGRATIONS.get(normalized)
    if migration is None:
        return None
    synthetic_type, training_path = migration
    return (
        f"`{normalized}` denotes a real training edit and cannot be generated by "
        "the generated-transformation materializer. "
        f"For a verifier-grade synthetic fixture use `{synthetic_type}`. "
        f"For training evidence use {training_path}."
    )


def reject_real_training_edit(edit_type: str) -> NoReturn:
    """Fail closed when a real training label reaches generated-edit code."""

    message = real_training_edit_migration_message(edit_type)
    if message is None:
        raise ValueError(f"Unsupported real training edit label: {edit_type!r}")
    raise ValueError(message)


@dataclass(frozen=True)
class ResolvedEditSpec:
    status: str
    edit_type: str
    param1: str = ""
    param2: str = ""
    scope: str = ""
    version: str = ""
    edit_dir_name: str = ""
    reason: str = ""
    requested_edit_type: str = ""

    @property
    def skip(self) -> bool:
        return self.status == "skipped"

    @property
    def selected(self) -> bool:
        return self.status == "selected"

    def to_shell_payload(self) -> dict[str, str]:
        return {
            "status": self.status,
            "reason": self.reason,
            "edit_type": self.edit_type,
            "requested_edit_type": self.requested_edit_type or self.edit_type,
            "param1": self.param1,
            "param2": self.param2,
            "scope": self.scope,
            "version": self.version,
            "edit_dir_name": self.edit_dir_name,
        }

    def to_batch_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {
            "type": self.edit_type,
            "requested_type": self.requested_edit_type or self.edit_type,
            "status": self.status,
            "reason": self.reason,
            "scope": self.scope,
            "edit_dir_name": self.edit_dir_name,
            "version": self.version,
        }
        if self.edit_type == "quant_rtn":
            payload["bits"] = (
                int(self.param1) if _safe_int(self.param1) is not None else 0
            )
            payload["group_size"] = (
                int(self.param2) if _safe_int(self.param2) is not None else 0
            )
        elif self.edit_type == "magnitude_prune":
            payload["ratio"] = (
                float(self.param1) if _safe_float(self.param1) is not None else 0.0
            )
        elif self.edit_type == SYNTHETIC_LOWRANK_DELTA:
            payload["rank"] = (
                int(self.param1) if _safe_int(self.param1) is not None else 0
            )
            payload["scale"] = (
                float(self.param2) if _safe_float(self.param2) is not None else 0.0
            )
        elif self.edit_type == SYNTHETIC_DENSE_UPDATE:
            payload["step_size"] = (
                float(self.param1) if _safe_float(self.param1) is not None else 0.0
            )
            payload["iterations"] = (
                int(self.param2) if _safe_int(self.param2) is not None else 0
            )
        return payload


def _safe_int(value: str) -> int | None:
    try:
        return int(value)
    except _COERCE_ERRORS:
        return None


def _safe_float(value: str) -> float | None:
    try:
        return float(value)
    except _COERCE_ERRORS:
        return None


def _normalize_non_quant_scope(
    edit_type: str,
    param1: str,
    param2: str,
    scope: str,
) -> tuple[str, str]:
    if edit_type != "quant_rtn" and not scope:
        scope = param2
        param2 = ""
    return param2, scope


def _normalize_quant_scope(param1: str, param2: str, scope: str) -> tuple[str, str]:
    if not scope and param1 and param2:
        scope = param2
        param2 = ""
    return param2, scope


def _canonical_directory_version(version: object) -> str:
    """Validate the one path component outside the transformation contract."""

    if not isinstance(version, str) or not _DIRECTORY_VERSION_RE.fullmatch(version):
        raise ValueError(
            "generated transformation version must be a non-empty lowercase path token"
        )
    return version


def _canonical_directory_sha256(payload: object) -> str:
    """Return the full digest of the exact identity encoded by a directory."""

    encoded = json.dumps(
        payload,
        allow_nan=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _directory_slug_atom(value: object) -> str:
    """Render a canonical contract value as an unambiguous safe path atom."""

    text = _canonical_float_text(value) if isinstance(value, float) else str(value)
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", text).strip("-")
    if not slug:
        raise ValueError("generated transformation directory component is empty")
    return slug


def generated_transformation_edit_dir_name(
    *,
    edit_type: object,
    parameters: Mapping[str, object],
    scope: object,
    version: object,
) -> str:
    """Return the immutable path for one canonical raw transformation.

    A generated artifact path is part of the evidence identity.  It therefore
    includes all canonical parameters and scope in readable form, plus the
    *full* digest of the versioned canonical identity.  Short descriptive
    names such as ``quant_4bit_clean`` were ambiguous: changing group size or
    scope silently targeted the same directory.  This helper intentionally
    has no fallback or legacy alias.
    """

    transformation = canonical_transformation_spec(edit_type, parameters)
    canonical_scope = validate_transformation_scope(scope)
    canonical_version = _canonical_directory_version(version)
    canonical_parameters = transformation["parameters"]
    if not isinstance(canonical_parameters, Mapping):  # contract invariant
        raise TransformationContractError("canonical transformation parameters missing")

    identity = {
        "schema": _GENERATED_TRANSFORMATION_DIRECTORY_SCHEMA,
        "transformation": transformation,
        "scope": canonical_scope,
        "version": canonical_version,
    }
    digest = _canonical_directory_sha256(identity)
    parameter_parts = [
        f"{key}-{_directory_slug_atom(value)}"
        for key, value in sorted(canonical_parameters.items())
    ]
    scope_part = _directory_slug_atom(canonical_scope)
    return "--".join(
        [
            "generated",
            str(transformation["edit_type"]),
            *parameter_parts,
            f"scope-{scope_part}",
            f"version-{canonical_version}",
            f"sha256-{digest}",
        ]
    )


def _default_edit_dir_name(
    *,
    edit_type: str,
    param1: str,
    param2: str,
    version: str,
    scope: str = "",
) -> str:
    if not version:
        return ""
    if edit_type == "quant_rtn":
        return generated_transformation_edit_dir_name(
            edit_type=edit_type,
            parameters={"bits": int(param1), "group_size": int(param2)},
            scope=scope,
            version=version,
        )
    if edit_type in {"bnb_4bit", "bnb_8bit"}:
        if version == "deployable":
            return f"quant_{param1}bit_deployable"
        return f"quant_{param1}bit_{version}"
    if edit_type == "magnitude_prune":
        try:
            pct = int(float(param1) * 100)
        except _COERCE_ERRORS:
            pct = 0
        return f"prune_{pct}pct_{version}"
    if edit_type == SYNTHETIC_LOWRANK_DELTA:
        return generated_transformation_edit_dir_name(
            edit_type=edit_type,
            parameters={"rank": int(param1), "scale": float(param2)},
            scope=scope,
            version=version,
        )
    if edit_type == SYNTHETIC_DENSE_UPDATE:
        return generated_transformation_edit_dir_name(
            edit_type=edit_type,
            parameters={"step_size": float(param1), "iterations": int(param2)},
            scope=scope,
            version=version,
        )
    return f"{edit_type}_{version}"


def _canonicalize_verifier_grade_fields(
    *,
    edit_type: str,
    param1: str,
    param2: str,
    scope: str,
) -> tuple[str, str, str]:
    """Validate resolver output against the one replay contract.

    The shell resolver is a public entry point, so it must not hand a
    generator a value that the materializer or replay validator would parse
    differently.  Convert the compact ``type:param1:param2:scope`` syntax to
    the exact typed parameter object accepted by the transformation contract,
    then return its canonical textual representation for the CLI payload.
    """

    if edit_type == "quant_rtn":
        parameters: dict[str, object] = {
            "bits": int(param1),
            "group_size": int(param2),
        }
    elif edit_type == SYNTHETIC_LOWRANK_DELTA:
        parameters = {"rank": int(param1), "scale": float(param2)}
    elif edit_type == SYNTHETIC_DENSE_UPDATE:
        parameters = {"step_size": float(param1), "iterations": int(param2)}
    else:  # defensive: callers gate this helper by the supported type set
        raise TransformationContractError(
            f"{edit_type!r} is not a verifier-grade generated transformation"
        )

    spec = canonical_transformation_spec(edit_type, parameters)
    canonical_parameters = spec["parameters"]
    if not isinstance(canonical_parameters, dict):  # contract invariant
        raise TransformationContractError("canonical transformation parameters missing")
    canonical_scope = validate_transformation_scope(scope)

    if edit_type == "quant_rtn":
        return (
            str(canonical_parameters["bits"]),
            str(canonical_parameters["group_size"]),
            canonical_scope,
        )
    if edit_type == SYNTHETIC_LOWRANK_DELTA:
        return (
            str(canonical_parameters["rank"]),
            _canonical_float_text(canonical_parameters["scale"]),
            canonical_scope,
        )
    return (
        _canonical_float_text(canonical_parameters["step_size"]),
        str(canonical_parameters["iterations"]),
        canonical_scope,
    )


def _canonical_float_text(value: object) -> str:
    """Render a finite canonical float without adding an unnecessary ``.0``."""

    normalized = float(value)
    if normalized.is_integer():
        return str(int(normalized))
    return repr(normalized)


def resolve_edit_spec(
    *,
    model_output_dir: Path,
    edit_spec: str,
    version_hint: str = "",
) -> ResolvedEditSpec:
    parts = edit_spec.split(":") if edit_spec else []
    requested_edit_type = parts[0] if parts else ""
    edit_type = requested_edit_type
    param1 = parts[1] if len(parts) > 1 else ""
    param2 = parts[2] if len(parts) > 2 else ""
    scope = parts[3] if len(parts) > 3 else ""

    migration_reason = real_training_edit_migration_message(requested_edit_type)
    if migration_reason is not None:
        return ResolvedEditSpec(
            status="invalid",
            reason=migration_reason,
            edit_type=edit_type,
            param1=param1,
            param2=param2,
            scope=scope,
            version=version_hint or ("clean" if param1 == "clean" else ""),
            requested_edit_type=requested_edit_type,
        )

    # FP8 simulation and in-memory SVD approximation do not have a
    # storage-level replay contract and are never valid generated-edit specs.
    if is_unverifiable_generated_edit_type(edit_type):
        return ResolvedEditSpec(
            status="invalid",
            reason="generated_edit_requires_dedicated_replay_contract",
            edit_type=edit_type,
            param1=param1,
            param2=param2,
            scope=scope,
            version=version_hint or ("clean" if param1 == "clean" else ""),
            requested_edit_type=requested_edit_type,
        )

    if edit_type in _VERIFIER_GRADE_TRANSFORMATION_TYPES:
        # The compact shell syntax is part of the artifact identity.  Do not
        # permit an ignored field, an omitted scope, or a scoped ``clean``
        # shorthand to collapse distinct user input onto one generated path.
        valid_arity = (
            len(parts) == 2
            if len(parts) >= 2 and parts[1] == "clean"
            else len(parts) == 4
        )
        if not valid_arity:
            return ResolvedEditSpec(
                status="invalid",
                reason="invalid_verifier_grade_transformation_arity",
                edit_type=edit_type,
                param1=param1,
                param2=param2,
                scope=scope,
                version=version_hint or ("clean" if param1 == "clean" else ""),
                requested_edit_type=requested_edit_type,
            )

    param2, scope = _normalize_non_quant_scope(edit_type, param1, param2, scope)
    if edit_type == "quant_rtn":
        param2, scope = _normalize_quant_scope(param1, param2, scope)

    clean_spec = param1 == "clean"
    if clean_spec:
        return ResolvedEditSpec(
            status="invalid",
            reason="clean_selection_requires_receipt",
            edit_type=edit_type,
            param1=param1,
            param2=param2,
            scope=scope,
            version=version_hint or "clean",
            requested_edit_type=requested_edit_type,
        )

    status = "selected"
    reason = ""
    edit_dir_name = ""

    if edit_type == "quant_rtn":
        if _safe_int(param1) is None or _safe_int(param2) is None:
            status = "invalid"
            reason = "invalid_quant_params"
    elif edit_type == "magnitude_prune":
        if _safe_float(param1) is None:
            status = "invalid"
            reason = "invalid_prune_sparsity"
    elif edit_type == SYNTHETIC_LOWRANK_DELTA:
        rank = _safe_int(param1)
        scale = _safe_float(param2)
        if rank is None or rank < 1:
            status = "invalid"
            reason = "invalid_synthetic_lowrank_rank"
        elif scale is None or scale <= 0:
            status = "invalid"
            reason = "invalid_synthetic_lowrank_scale"
    elif edit_type == SYNTHETIC_DENSE_UPDATE:
        step_size = _safe_float(param1)
        iterations = _safe_int(param2)
        if step_size is None or step_size <= 0:
            status = "invalid"
            reason = "invalid_synthetic_dense_step_size"
        elif iterations is None or iterations < 1:
            status = "invalid"
            reason = "invalid_synthetic_dense_iterations"
    elif edit_type in {"bnb_4bit", "bnb_8bit"}:
        expected_bits = "4" if edit_type == "bnb_4bit" else "8"
        if param1 != expected_bits:
            status = "invalid"
            reason = "invalid_bitsandbytes_bitwidth"
        elif scope != "all":
            status = "invalid"
            reason = "bitsandbytes_scope_must_be_all"

    if status == "selected" and edit_type in _VERIFIER_GRADE_TRANSFORMATION_TYPES:
        try:
            param1, param2, scope = _canonicalize_verifier_grade_fields(
                edit_type=edit_type,
                param1=param1,
                param2=param2,
                scope=scope,
            )
        except (TransformationContractError, ValueError, OverflowError):
            status = "invalid"
            reason = "invalid_verifier_grade_transformation_contract"

    version = version_hint or ("clean" if clean_spec else "")
    if status == "selected" and not edit_dir_name:
        edit_dir_name = _default_edit_dir_name(
            edit_type=edit_type,
            param1=param1,
            param2=param2,
            version=version,
            scope=scope,
        )

    return ResolvedEditSpec(
        status=status,
        reason=reason,
        edit_type=edit_type,
        param1=param1,
        param2=param2,
        scope=scope,
        version=version,
        edit_dir_name=edit_dir_name,
        requested_edit_type=requested_edit_type,
    )


def parse_edit_specs_json(raw_payload: str) -> list[object]:
    try:
        edit_specs = json.loads(raw_payload)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid edit_specs JSON: {exc}") from exc

    if not isinstance(edit_specs, list):
        raise ValueError("edit_specs_json must be a JSON list")
    return edit_specs


def resolve_batch_entry(
    *,
    spec_entry: object,
    model_output_dir: Path,
) -> ResolvedEditSpec | None:
    if not isinstance(spec_entry, dict):
        return None
    spec_str = str(spec_entry.get("spec", ""))
    version = str(spec_entry.get("version", "clean"))
    return resolve_edit_spec(
        model_output_dir=model_output_dir,
        edit_spec=spec_str,
        version_hint=version,
    )


def normalize_coverage(coverage: dict[str, object] | None) -> dict[str, object]:
    coverage = coverage if isinstance(coverage, dict) else {}
    if "edited_count" in coverage:
        raise ValueError("coverage.edited_count is unsupported; use edited_tensors")
    normalized: dict[str, object] = {
        "edited_tensors": coverage.get("edited_tensors", 0),
        "edited_params": coverage.get("edited_params", 0),
        "total_params": coverage.get("total_params", 0),
        "coverage_ratio": coverage.get("coverage_ratio", 0.0),
    }
    edited_params = normalized["edited_params"]
    total_params = normalized["total_params"]
    if (
        isinstance(edited_params, int)
        and not isinstance(edited_params, bool)
        and isinstance(total_params, int)
        and not isinstance(total_params, bool)
        and edited_params >= 0
        and total_params > 0
        and "coverage_ratio" not in coverage
    ):
        normalized["coverage_ratio"] = edited_params / total_params
    validation_errors = edit_metadata_coverage_errors(
        {"coverage": normalized}, require_positive=False
    )
    if validation_errors:
        raise ValueError("; ".join(validation_errors))
    return normalized


def build_edit_metadata(
    *,
    edit_type: str,
    scope: str,
    parameters: dict[str, object] | None = None,
    coverage: dict[str, object] | None = None,
    artifact_class: str = VALIDATION_SUBJECT_CHECKPOINT,
    edit_semantics: str = EDIT_SEMANTICS_EXTERNAL_SUBJECT,
    deployable_as_hf_checkpoint: bool = True,
    optimized_deployment_backend: bool = False,
    backend: str | None = None,
    storage_format: str | None = None,
    actual_storage_format: str | None = None,
    packed_quantized_storage: bool = False,
    runtime_memory_reduction: bool = False,
    runtime_memory_reduction_expected: bool | None = None,
    run_directory_contains_edit_artifacts: bool = True,
    edit_provenance: dict[str, object] | None = None,
    edit_impact: dict[str, object] | None = None,
    extra: dict[str, object] | None = None,
) -> dict[str, object]:
    canonical_storage = storage_format_for_edit(edit_type)
    resolved_storage = storage_format or canonical_storage
    normalized_coverage = normalize_coverage(coverage)
    if artifact_class in {
        VALIDATION_SUBJECT_CHECKPOINT,
        DEPLOYABLE_OPTIMIZED_SUBJECT,
    }:
        coverage_errors = edit_metadata_coverage_errors(
            {"coverage": normalized_coverage}, require_positive=True
        )
        if coverage_errors:
            raise ValueError("; ".join(coverage_errors))
    metadata: dict[str, object] = {
        "schema": EDIT_METADATA_SCHEMA,
        "artifact_class": artifact_class,
        "edit_type": edit_type,
        "edit_semantics": edit_semantics,
        "deployable_as_hf_checkpoint": bool(deployable_as_hf_checkpoint),
        "optimized_deployment_backend": bool(optimized_deployment_backend),
        "backend": backend,
        "storage_format": resolved_storage,
        "actual_storage_format": actual_storage_format or resolved_storage,
        "packed_quantized_storage": bool(packed_quantized_storage),
        "runtime_memory_reduction": bool(runtime_memory_reduction),
        "runtime_memory_reduction_expected": (
            bool(runtime_memory_reduction_expected)
            if runtime_memory_reduction_expected is not None
            else bool(runtime_memory_reduction)
        ),
        "run_directory_contains_edit_artifacts": bool(
            run_directory_contains_edit_artifacts
        ),
        "scope": scope,
        "parameters": dict(parameters or {}),
        "coverage": normalized_coverage,
    }
    if edit_provenance is not None:
        metadata["edit_provenance"] = dict(edit_provenance)
    if edit_impact is not None:
        metadata["edit_impact"] = dict(edit_impact)
    if extra:
        metadata.update(extra)
    return metadata


def build_validation_edit_metadata(
    *,
    edit_type: str,
    scope: str,
    parameters: dict[str, object] | None = None,
    coverage: dict[str, object] | None = None,
    edit_provenance: dict[str, object] | None = None,
    edit_impact: dict[str, object] | None = None,
    extra: dict[str, object] | None = None,
) -> dict[str, object]:
    return build_edit_metadata(
        edit_type=edit_type,
        scope=scope,
        parameters=parameters,
        coverage=coverage,
        artifact_class=VALIDATION_SUBJECT_CHECKPOINT,
        edit_semantics=EDIT_SEMANTICS_EXTERNAL_SUBJECT,
        deployable_as_hf_checkpoint=True,
        optimized_deployment_backend=False,
        backend=None,
        storage_format=storage_format_for_edit(edit_type),
        actual_storage_format=storage_format_for_edit(edit_type),
        packed_quantized_storage=False,
        runtime_memory_reduction=False,
        runtime_memory_reduction_expected=False,
        edit_provenance=edit_provenance,
        edit_impact=edit_impact,
        extra=extra,
    )


def write_edit_metadata(path: Path, metadata: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n")


def read_edit_metadata(path: Path) -> dict[str, object]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("edit metadata must be a JSON object")
    return payload


def validate_edit_metadata(
    metadata: dict[str, object],
    *,
    expected_edit_type: str | None = None,
    expected_artifact_class: str | None = None,
) -> list[str]:
    return _validate_edit_metadata_contract(
        metadata,
        expected_edit_type=expected_edit_type,
        expected_artifact_class=expected_artifact_class,
    )


__all__ = [
    "ALLOWED_ARTIFACT_CLASSES",
    "DEPLOYABLE_OPTIMIZED_SUBJECT",
    "EDIT_METADATA_SCHEMA",
    "EDIT_IMPACT_SCENARIO_TYPES",
    "EDIT_TOPOLOGY_ARTIFACT_KINDS",
    "EDIT_SEMANTICS_DEPLOYABLE",
    "EDIT_SEMANTICS_EXTERNAL_SUBJECT",
    "DELTA_AVAILABILITY_VALUES",
    "EVIDENCE_ONLY_PACK",
    "FAULT_INJECTION_FIXTURE",
    "PRIVACY_SENSITIVITY_VALUES",
    "REAL_TRAINING_EDIT_MIGRATIONS",
    "ResolvedEditSpec",
    "SYNTHETIC_DENSE_UPDATE",
    "SYNTHETIC_LOWRANK_DELTA",
    "VALIDATION_SUBJECT_CHECKPOINT",
    "build_edit_metadata",
    "build_validation_edit_metadata",
    "generated_transformation_edit_dir_name",
    "normalize_coverage",
    "parse_edit_specs_json",
    "read_edit_metadata",
    "real_training_edit_migration_message",
    "reject_real_training_edit",
    "resolve_batch_entry",
    "resolve_edit_spec",
    "storage_format_for_edit",
    "validate_edit_metadata",
    "write_edit_metadata",
]
