"""Real pathname mutations at the file publication boundary."""

import errno
import os
import sys

import pytest

from invarlock.filesystem import atomic_file as target
from invarlock.filesystem.paths import PathChangedError, pinned_directory


@pytest.mark.skipif(
    sys.platform != "linux" or os.geteuid() == 0,
    reason="requires Linux directory traversal with non-root permissions",
)
@pytest.mark.parametrize("ancestor_mode", [0o100, 0o300])
def test_publication_and_reading_through_non_listable_ancestor(tmp_path, ancestor_mode):
    ancestor = tmp_path / "worker-output"
    directory = ancestor / "sidecars"
    directory.mkdir(parents=True)
    destination = directory / "identity.json"
    ancestor.chmod(ancestor_mode)
    try:
        with pytest.raises(PermissionError):
            os.listdir(ancestor)
        target.write_file_no_replace(destination, b"complete sidecar")
        with pinned_directory(directory) as descriptor:
            assert os.listdir(descriptor) == [destination.name]
            os.fsync(descriptor)
            file_fd = os.open(destination.name, os.O_RDONLY, dir_fd=descriptor)
            with os.fdopen(file_fd, "rb") as handle:
                assert handle.read() == b"complete sidecar"
    finally:
        ancestor.chmod(0o700)
    assert list(directory.iterdir()) == [destination]


@pytest.mark.skipif(
    sys.platform != "linux" or os.geteuid() == 0,
    reason="requires Linux directory traversal with non-root permissions",
)
def test_final_directory_still_requires_read_permission(tmp_path):
    directory = tmp_path / "sidecars"
    directory.mkdir(mode=0o300)
    try:
        with pytest.raises(PermissionError):
            target.write_file_no_replace(directory / "identity.json", b"sidecar")
    finally:
        directory.chmod(0o700)
    assert not list(directory.iterdir())


@pytest.mark.parametrize("replacement", ["source", "destination", "contents"])
def test_substitution_at_kernel_publication_never_reports_success(
    tmp_path, monkeypatch, replacement
):
    destination = tmp_path / "result"
    rename = target._rename_no_replace

    def substitute(**kwargs):
        stage = kwargs["source_parent_fd"]
        if replacement == "source":
            os.rename("payload", "original", src_dir_fd=stage, dst_dir_fd=stage)
            descriptor = os.open(
                "payload", os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600, dir_fd=stage
            )
            with os.fdopen(descriptor, "wb") as handle:
                handle.write(b"untrusted replacement")
        elif replacement == "contents":
            descriptor = os.open("payload", os.O_WRONLY | os.O_TRUNC, dir_fd=stage)
            with os.fdopen(descriptor, "wb") as handle:
                handle.write(b"changed contents")
        result = rename(**kwargs)
        if replacement == "destination":
            destination.unlink()
            destination.write_bytes(b"independent replacement")
        return result

    monkeypatch.setattr(target, "_rename_no_replace", substitute)
    with pytest.raises(PathChangedError, match="published file identity changed"):
        target.write_file_no_replace(destination, b"generated bytes")
    # A post-commit mismatch is ambiguous: never delete an independent entry.
    assert destination.exists()


def test_named_source_substitution_before_commit_is_rejected(tmp_path, monkeypatch):
    destination = tmp_path / "result"
    fstat = os.fstat
    replaced = False

    def replace_before_check(descriptor):
        nonlocal replaced
        value = fstat(descriptor)
        if value.st_size == len(b"generated bytes") and not replaced:
            for stage in tmp_path.glob(".invarlock-write-*"):
                if (stage / "payload").exists():
                    replaced = True
                    (stage / "payload").rename(stage / "original")
                    (stage / "payload").write_bytes(b"replacement")
        return value

    monkeypatch.setattr(os, "fstat", replace_before_check)
    with pytest.raises(PathChangedError, match="before publication"):
        target.write_file_no_replace(destination, b"generated bytes")
    assert replaced and not destination.exists()
    assert (
        next(tmp_path.glob(".invarlock-write-*/payload")).read_bytes() == b"replacement"
    )


def test_parent_replacement_does_not_return_an_unrelated_output(tmp_path, monkeypatch):
    parent = tmp_path / "parent"
    parent.mkdir()
    destination = parent / "result"
    moved = tmp_path / "moved"
    rename = target._rename_no_replace

    def replace_parent(**kwargs):
        parent.rename(moved)
        parent.mkdir()
        destination.write_bytes(b"independent output")
        return rename(**kwargs)

    monkeypatch.setattr(target, "_rename_no_replace", replace_parent)
    with pytest.raises(PathChangedError, match="directory source was replaced"):
        target.write_file_no_replace(destination, b"generated bytes")
    assert destination.read_bytes() == b"independent output"
    assert (moved / "result").read_bytes() == b"generated bytes"


def test_renamed_private_stage_remains_the_source(tmp_path, monkeypatch):
    destination = tmp_path / "result"
    rename = target._rename_no_replace

    def replace_stage(**kwargs):
        stage = next(tmp_path.glob(".invarlock-write-*"))
        stage.rename(tmp_path / "moved-stage")
        stage.mkdir()
        (stage / "foreign").write_bytes(b"preserve")
        return rename(**kwargs)

    monkeypatch.setattr(target, "_rename_no_replace", replace_stage)
    target.write_file_no_replace(destination, b"generated bytes")
    assert destination.read_bytes() == b"generated bytes"
    assert next(tmp_path.glob(".invarlock-write-*/foreign")).read_bytes() == b"preserve"


@pytest.mark.parametrize("replace_with_nonempty", [False, True])
def test_failed_stage_open_removes_at_most_an_empty_directory(
    tmp_path, monkeypatch, replace_with_nonempty
):
    real_open = os.open

    def fail_stage(name, flags, *args, **kwargs):
        if str(name).startswith(".invarlock-write-"):
            if replace_with_nonempty:
                (tmp_path / name / "foreign").write_bytes(b"preserve")
            raise OSError(errno.EMFILE, "stage open failed")
        return real_open(name, flags, *args, **kwargs)

    monkeypatch.setattr(os, "open", fail_stage)
    with pytest.raises(OSError, match="stage open failed"):
        target.write_file_no_replace(tmp_path / "result", b"generated bytes")
    if replace_with_nonempty:
        assert (
            next(tmp_path.glob(".invarlock-write-*/foreign")).read_bytes()
            == b"preserve"
        )
    else:
        assert not list(tmp_path.iterdir())


def test_private_stage_rejects_changed_permissions(tmp_path, monkeypatch):
    real_open = os.open

    def open_changed_stage(name, flags, *args, **kwargs):
        descriptor = real_open(name, flags, *args, **kwargs)
        if str(name).startswith(".invarlock-write-"):
            os.fchmod(descriptor, 0o755)
        return descriptor

    monkeypatch.setattr(os, "open", open_changed_stage)
    with pytest.raises(PathChangedError, match="private staging directory"):
        target.write_file_no_replace(tmp_path / "result", b"generated bytes")
    assert not list(tmp_path.iterdir())


def test_sync_after_rename_retains_complete_destination_on_failure(
    tmp_path, monkeypatch
):
    destination = tmp_path / "result"
    real_fsync = os.fsync
    synced_after_commit = []

    def sync(descriptor):
        if destination.exists():
            synced_after_commit.append(descriptor)
            raise OSError(errno.EIO, "directory sync failed after commit")
        return real_fsync(descriptor)

    monkeypatch.setattr(os, "fsync", sync)
    with pytest.raises(OSError, match="after commit"):
        target.write_file_no_replace(destination, b"generated bytes")
    assert synced_after_commit
    assert destination.read_bytes() == b"generated bytes"
    assert list(tmp_path.iterdir()) == [destination]


def test_existing_destination_is_preserved(tmp_path):
    destination = tmp_path / "result"
    destination.write_bytes(b"existing")
    with pytest.raises(FileExistsError):
        target.write_file_no_replace(destination, b"generated bytes")
    assert destination.read_bytes() == b"existing"


def test_new_parent_and_readonly_file_modes(tmp_path):
    destination = tmp_path / "new" / "result"
    target.write_file_no_replace(destination, b"generated bytes", mode=0o444)
    assert destination.read_bytes() == b"generated bytes"
    assert destination.stat().st_mode & 0o777 == 0o444
    assert destination.parent.stat().st_mode & 0o777 == 0o700
