#!/usr/bin/env bash

# Shared preflight helpers for integration example runners. Source this file
# after SCRIPT_DIR, REPO_ROOT, and PYTHON_BIN have been resolved.

integration_log_header() {
  local title="$1"
  printf '\n==> %s\n' "$title" >&2
}

integration_log_step() {
  local message="$1"
  printf '  -> %s\n' "$message" >&2
}

integration_log_kv() {
  local key="$1"
  local value="$2"
  printf '     %s: %s\n' "$key" "${value:-<unset>}" >&2
}

integration_filter_source_archive_stderr() {
  local line

  while IFS= read -r line; do
    case "$line" in
      "fatal: not a git repository (or any of the parent directories): .git")
        ;;
      *)
        printf '%s\n' "$line" >&2
        ;;
    esac
  done
}

integration_run_source_archive_clean() {
  if [[ -n "${REPO_ROOT:-}" && -d "$REPO_ROOT/.git" ]]; then
    "$@"
  else
    local stderr_file
    stderr_file="$(mktemp "${TMPDIR:-/tmp}/invarlock-source-archive-stderr.XXXXXX")" || return 1
    local had_errexit=0
    case "$-" in
      *e*)
        had_errexit=1
        set +e
        ;;
    esac
    "$@" 2>"$stderr_file"
    local rc=$?
    if [[ "$had_errexit" == "1" ]]; then
      set -e
    fi
    integration_filter_source_archive_stderr <"$stderr_file"
    rm -f "$stderr_file"
    return "$rc"
  fi
}

integration_effective_execution_mode() {
  local lane="$1"
  local execution_mode="$2"

  case "$lane" in
    host)
      printf 'host\n'
      ;;
    cuda)
      printf 'container\n'
      ;;
    *)
      printf '%s\n' "$execution_mode"
      ;;
  esac
}

integration_effective_assurance() {
  local lane="$1"
  local assurance="$2"

  case "$lane" in
    host)
      printf 'off\n'
      ;;
    cuda)
      printf 'strict\n'
      ;;
    *)
      printf '%s\n' "$assurance"
      ;;
  esac
}

integration_effective_device() {
  local lane="$1"
  local device="$2"

  case "$lane" in
    cuda)
      printf 'cuda\n'
      ;;
    *)
      printf '%s\n' "$device"
      ;;
  esac
}

integration_default_host_device() {
  local execution_mode="$1"
  local device="$2"

  if [[ "$execution_mode" == "host" && -z "$device" ]]; then
    printf 'cpu\n'
    return 0
  fi

  printf '%s\n' "$device"
}

integration_require_strict_runtime_pin() {
  local assurance="$1"
  local expected_digest="${2:-${INVARLOCK_EXPECTED_RUNTIME_IMAGE_DIGEST:-}}"

  if [[ "$assurance" == "strict" && -z "$expected_digest" ]]; then
    cat >&2 <<'MSG'
Strict assurance requires an independently supplied runtime image pin. Pass
--expected-runtime-image-digest to the shared wrapper or set the wrapper-only
INVARLOCK_EXPECTED_RUNTIME_IMAGE_DIGEST variable from a source independent of
the generated report and runtime manifest.
MSG
    return 2
  fi
}

integration_require_strict_acceptance_inputs() {
  local assurance="$1"
  local expected_digest="$2"
  local baseline_report="$3"
  local policy_pack="$4"

  if [[ "$assurance" != "strict" ]]; then
    return 0
  fi

  integration_require_strict_runtime_pin "$assurance" "$expected_digest" || return $?
  if [[ ! "$expected_digest" =~ ^sha256:[a-f0-9]{64}$ ]]; then
    echo "Strict assurance runtime image pin must be a canonical sha256 digest." >&2
    return 2
  fi

  if [[ -z "$baseline_report" ]]; then
    cat >&2 <<'MSG'
Strict assurance requires an independently supplied raw baseline report. Pass
--baseline-report to the shared wrapper or set the wrapper-only
INVARLOCK_ACCEPTANCE_BASELINE_REPORT variable. The baseline must be supplied
independently of the subject evaluation generated by this wrapper.
MSG
    return 2
  fi
  if [[ ! -f "$baseline_report" || ! -s "$baseline_report" ]]; then
    printf 'Strict assurance baseline report is not a non-empty file: %s\n' \
      "$baseline_report" >&2
    return 2
  fi
  if ! integration_require_json_object "$baseline_report" "baseline report"; then
    return 2
  fi

  if [[ -z "$policy_pack" ]]; then
    cat >&2 <<'MSG'
Strict assurance requires an independently supplied policy pack. Pass --policy-pack
to the shared wrapper or set the wrapper-only INVARLOCK_ACCEPTANCE_POLICY_PACK
variable so the generated report cannot authorize its own thresholds.
MSG
    return 2
  fi
  if [[ ! -f "$policy_pack" || ! -s "$policy_pack" ]]; then
    printf 'Strict assurance policy pack is not a non-empty file: %s\n' \
      "$policy_pack" >&2
    return 2
  fi
  if ! integration_require_json_object "$policy_pack" "policy pack"; then
    return 2
  fi
}

integration_require_json_object() {
  local path="$1"
  local label="$2"
  local python_bin="${PYTHON_BIN:-}"
  if [[ -z "$python_bin" ]]; then
    if command -v python3 >/dev/null 2>&1; then
      python_bin="python3"
    elif command -v python >/dev/null 2>&1; then
      python_bin="python"
    else
      echo "Cannot validate strict acceptance JSON: no Python interpreter found." >&2
      return 2
    fi
  fi
  if ! "$python_bin" - "$path" <<'PY'
import json
from pathlib import Path
import sys

path = Path(sys.argv[1])
try:
    payload = json.loads(path.read_text(encoding="utf-8"))
except (OSError, UnicodeError, json.JSONDecodeError) as exc:
    raise SystemExit(f"invalid JSON: {exc}") from exc
if not isinstance(payload, dict):
    raise SystemExit("JSON root must be an object")
PY
  then
    printf 'Strict assurance %s must contain one valid JSON object: %s\n' \
      "$label" "$path" >&2
    return 2
  fi
}

integration_lane_artifact_label() {
  local execution_mode="$1"
  local assurance="$2"
  local device="$3"

  if [[ "$execution_mode" == "container" && "$assurance" == "strict" && "$device" == cuda* ]]; then
    printf 'cuda-container-strict\n'
    return 0
  fi

  if [[ "$execution_mode" == "host" && "$assurance" == "off" ]]; then
    case "$device" in
      cuda*)
        printf 'cuda-host-off\n'
        ;;
      mps*)
        printf 'mps-host-off\n'
        ;;
      *)
        printf 'cpu-host-off\n'
        ;;
    esac
    return 0
  fi

  printf '%s-%s-%s\n' "${device:-auto}" "$execution_mode" "$assurance"
}

integration_lane_report_out() {
  local report_out="$1"
  local report_out_was_default="$2"
  local lane_artifact_label="$3"

  if [[ "$report_out_was_default" == "1" ]]; then
    printf '%s/%s\n' "$report_out" "$lane_artifact_label"
    return 0
  fi

  printf '%s\n' "$report_out"
}

integration_preflight_host_cuda_device() {
  local python_bin="$1"
  local execution_mode="$2"
  local device="$3"
  local example_name="$4"

  if [[ "$execution_mode" != "host" || "$device" != cuda* ]]; then
    return 0
  fi

  if ! "$python_bin" -c 'import torch; raise SystemExit(0 if torch.cuda.is_available() else 1)' >/dev/null 2>&1; then
    cat >&2 <<MSG
$example_name host CUDA lane requires torch.cuda to be available.

Use --device cpu for a cpu-host-off run when the backend supports CPU, or use
--lane cuda with the documented runtime image for container-backed strict
evidence on a CUDA host.
MSG
    return 2
  fi
}

integration_preflight_gptqmodel_host_runtime() {
  local python_bin="$1"
  local execution_mode="$2"
  local device="${3:-}"

  if [[ "$execution_mode" != "host" || "$device" != cuda* ]]; then
    return 0
  fi

  if ! "$python_bin" -c 'from invarlock.gptqmodel_runtime import require_gptqmodel_runtime; require_gptqmodel_runtime(require_jit_toolchain=True)' >/dev/null 2>&1; then
    cat >&2 <<'MSG'
GPTQModel CUDA host lanes require the GPTQModel CUDA JIT toolchain because
kernel helpers may compile during model loading.

Install a C++ compiler, ninja, matching Python development headers, and a CUDA
toolkit with nvcc for the active interpreter, or use --lane cuda with the
documented container image for strict evidence.
MSG
    return 2
  fi
}
